/**
 * Seed danh muc khoa lam sang, ban kham va giuong noi bo (Mau 01).
 * Nguon: C:\\Users\\admin\\Documents\\Google Drive\\BHYT\\PC CT\\FileKhoaPhongGiuong.xlsx
 * Cap nhat: 2026-06-23
 */

export const PHIEN_BAN_DANH_MUC_KHOA_LS_M01 = '2026-06-23-pc-can-tho-m01-26';

export const COT_DANH_MUC_KHOA_LS_M01 = [
  "STT",
  "MA_KHOA",
  "TEN_KHOA",
  "BAN_KHAM",
  "GIUONG_PD",
  "GIUONG_TK",
  "GIUONG_HSTC",
  "GIUONG_HSCC",
  "TU_NGAY",
  "DEN_NGAY",
  "MA_CSKCB",
  "ID",
  "MA_LOAI_KCB",
  "LDLK",
  "LIEN_KHOA",
  "GIUONG_2015"
];

export const DANH_MUC_KHOA_LS_M01 = [

  {
    "STT": 1,
    "MA_KHOA": "K30",
    "TEN_KHOA": "Khoa Mắt",
    "BAN_KHAM": "",
    "GIUONG_PD": 4,
    "GIUONG_TK": 4,
    "GIUONG_HSTC": "",
    "GIUONG_HSCC": "",
    "TU_NGAY": "",
    "DEN_NGAY": "",
    "MA_CSKCB": 92114,
    "ID": 437125,
    "MA_LOAI_KCB": 4,
    "LDLK": 2,
    "LIEN_KHOA": "",
    "GIUONG_2015": ""
  },
  {
    "STT": 2,
    "MA_KHOA": "02.05",
    "TEN_KHOA": "Nội tiêu hóa",
    "BAN_KHAM": 1,
    "GIUONG_PD": "",
    "GIUONG_TK": "",
    "GIUONG_HSTC": "",
    "GIUONG_HSCC": "",
    "TU_NGAY": "",
    "DEN_NGAY": "",
    "MA_CSKCB": 92114,
    "ID": 437126,
    "MA_LOAI_KCB": 1,
    "LDLK": 2,
    "LIEN_KHOA": "",
    "GIUONG_2015": ""
  },
  {
    "STT": 3,
    "MA_KHOA": "02.08",
    "TEN_KHOA": "Nội tiết",
    "BAN_KHAM": 1,
    "GIUONG_PD": "",
    "GIUONG_TK": "",
    "GIUONG_HSTC": "",
    "GIUONG_HSCC": "",
    "TU_NGAY": "",
    "DEN_NGAY": "",
    "MA_CSKCB": 92114,
    "ID": 437127,
    "MA_LOAI_KCB": 1,
    "LDLK": 2,
    "LIEN_KHOA": "",
    "GIUONG_2015": ""
  },
  {
    "STT": 4,
    "MA_KHOA": "16.29",
    "TEN_KHOA": "Răng - Hàm - Mặt",
    "BAN_KHAM": 2,
    "GIUONG_PD": "",
    "GIUONG_TK": "",
    "GIUONG_HSTC": "",
    "GIUONG_HSCC": "",
    "TU_NGAY": "",
    "DEN_NGAY": "",
    "MA_CSKCB": 92114,
    "ID": 437128,
    "MA_LOAI_KCB": 1,
    "LDLK": 2,
    "LIEN_KHOA": "",
    "GIUONG_2015": ""
  },
  {
    "STT": 5,
    "MA_KHOA": "13.27",
    "TEN_KHOA": "Phụ sản",
    "BAN_KHAM": 13,
    "GIUONG_PD": "",
    "GIUONG_TK": "",
    "GIUONG_HSTC": "",
    "GIUONG_HSCC": "",
    "TU_NGAY": "",
    "DEN_NGAY": "",
    "MA_CSKCB": 92114,
    "ID": 437129,
    "MA_LOAI_KCB": 1,
    "LDLK": 2,
    "LIEN_KHOA": "",
    "GIUONG_2015": ""
  },
  {
    "STT": 6,
    "MA_KHOA": "K26",
    "TEN_KHOA": "Khoa Phẫu thuật – Gây mê hồi sức",
    "BAN_KHAM": "",
    "GIUONG_PD": 10,
    "GIUONG_TK": 10,
    "GIUONG_HSTC": "",
    "GIUONG_HSCC": "",
    "TU_NGAY": "",
    "DEN_NGAY": "",
    "MA_CSKCB": 92114,
    "ID": 437150,
    "MA_LOAI_KCB": 4,
    "LDLK": 2,
    "LIEN_KHOA": "",
    "GIUONG_2015": ""
  },
  {
    "STT": 7,
    "MA_KHOA": "K03",
    "TEN_KHOA": "Khoa Nội tổng hợp",
    "BAN_KHAM": "",
    "GIUONG_PD": 10,
    "GIUONG_TK": 10,
    "GIUONG_HSTC": "",
    "GIUONG_HSCC": "",
    "TU_NGAY": "",
    "DEN_NGAY": "",
    "MA_CSKCB": 92114,
    "ID": 437151,
    "MA_LOAI_KCB": 4,
    "LDLK": 2,
    "LIEN_KHOA": "",
    "GIUONG_2015": ""
  },
  {
    "STT": 8,
    "MA_KHOA": "K19",
    "TEN_KHOA": "Khoa Ngoại tổng hợp",
    "BAN_KHAM": "",
    "GIUONG_PD": 8,
    "GIUONG_TK": 8,
    "GIUONG_HSTC": "",
    "GIUONG_HSCC": "",
    "TU_NGAY": "",
    "DEN_NGAY": "",
    "MA_CSKCB": 92114,
    "ID": 437153,
    "MA_LOAI_KCB": 4,
    "LDLK": 2,
    "LIEN_KHOA": "",
    "GIUONG_2015": ""
  },
  {
    "STT": 9,
    "MA_KHOA": "K28",
    "TEN_KHOA": "Khoa Tai - Mũi - Họng",
    "BAN_KHAM": "",
    "GIUONG_PD": 4,
    "GIUONG_TK": 4,
    "GIUONG_HSTC": "",
    "GIUONG_HSCC": "",
    "TU_NGAY": "",
    "DEN_NGAY": "",
    "MA_CSKCB": 92114,
    "ID": 437154,
    "MA_LOAI_KCB": 4,
    "LDLK": 2,
    "LIEN_KHOA": "",
    "GIUONG_2015": ""
  },
  {
    "STT": 10,
    "MA_KHOA": "02.03",
    "TEN_KHOA": "Nội tổng hợp",
    "BAN_KHAM": 1,
    "GIUONG_PD": "",
    "GIUONG_TK": "",
    "GIUONG_HSTC": "",
    "GIUONG_HSCC": "",
    "TU_NGAY": "",
    "DEN_NGAY": "",
    "MA_CSKCB": 92114,
    "ID": 437156,
    "MA_LOAI_KCB": 1,
    "LDLK": 2,
    "LIEN_KHOA": "",
    "GIUONG_2015": ""
  },
  {
    "STT": 11,
    "MA_KHOA": "14.30",
    "TEN_KHOA": "Mắt",
    "BAN_KHAM": 3,
    "GIUONG_PD": "",
    "GIUONG_TK": "",
    "GIUONG_HSTC": "",
    "GIUONG_HSCC": "",
    "TU_NGAY": "",
    "DEN_NGAY": "",
    "MA_CSKCB": 92114,
    "ID": 437157,
    "MA_LOAI_KCB": 1,
    "LDLK": 2,
    "LIEN_KHOA": "",
    "GIUONG_2015": ""
  },
  {
    "STT": 12,
    "MA_KHOA": "15.28",
    "TEN_KHOA": "Tai - Mũi - Họng",
    "BAN_KHAM": 3,
    "GIUONG_PD": "",
    "GIUONG_TK": "",
    "GIUONG_HSTC": "",
    "GIUONG_HSCC": "",
    "TU_NGAY": "",
    "DEN_NGAY": "",
    "MA_CSKCB": 92114,
    "ID": 437158,
    "MA_LOAI_KCB": 1,
    "LDLK": 2,
    "LIEN_KHOA": "",
    "GIUONG_2015": ""
  },
  {
    "STT": 13,
    "MA_KHOA": "03.18",
    "TEN_KHOA": "Nhi",
    "BAN_KHAM": 11,
    "GIUONG_PD": "",
    "GIUONG_TK": "",
    "GIUONG_HSTC": "",
    "GIUONG_HSCC": "",
    "TU_NGAY": "",
    "DEN_NGAY": "",
    "MA_CSKCB": 92114,
    "ID": 437159,
    "MA_LOAI_KCB": 1,
    "LDLK": 2,
    "LIEN_KHOA": "",
    "GIUONG_2015": ""
  },
  {
    "STT": 14,
    "MA_KHOA": "K41",
    "TEN_KHOA": "Khoa Nội soi",
    "BAN_KHAM": "",
    "GIUONG_PD": 17,
    "GIUONG_TK": 17,
    "GIUONG_HSTC": "",
    "GIUONG_HSCC": "",
    "TU_NGAY": "",
    "DEN_NGAY": "",
    "MA_CSKCB": 92114,
    "ID": 437160,
    "MA_LOAI_KCB": 4,
    "LDLK": 2,
    "LIEN_KHOA": "",
    "GIUONG_2015": ""
  },
  {
    "STT": 15,
    "MA_KHOA": "K18",
    "TEN_KHOA": "Khoa Nhi",
    "BAN_KHAM": "",
    "GIUONG_PD": 22,
    "GIUONG_TK": 22,
    "GIUONG_HSTC": "",
    "GIUONG_HSCC": "",
    "TU_NGAY": "",
    "DEN_NGAY": "",
    "MA_CSKCB": 92114,
    "ID": 437161,
    "MA_LOAI_KCB": 4,
    "LDLK": 2,
    "LIEN_KHOA": "",
    "GIUONG_2015": ""
  },
  {
    "STT": 16,
    "MA_KHOA": "K39",
    "TEN_KHOA": "Khoa Chẩn đoán hình ảnh",
    "BAN_KHAM": "",
    "GIUONG_PD": "",
    "GIUONG_TK": "",
    "GIUONG_HSTC": "",
    "GIUONG_HSCC": "",
    "TU_NGAY": "",
    "DEN_NGAY": "",
    "MA_CSKCB": 92114,
    "ID": 437162,
    "MA_LOAI_KCB": "",
    "LDLK": 2,
    "LIEN_KHOA": "",
    "GIUONG_2015": ""
  },
  {
    "STT": 17,
    "MA_KHOA": "02.11",
    "TEN_KHOA": "Truyền nhiễm",
    "BAN_KHAM": 1,
    "GIUONG_PD": "",
    "GIUONG_TK": "",
    "GIUONG_HSTC": "",
    "GIUONG_HSCC": "",
    "TU_NGAY": "",
    "DEN_NGAY": "",
    "MA_CSKCB": 92114,
    "ID": 437163,
    "MA_LOAI_KCB": 1,
    "LDLK": 2,
    "LIEN_KHOA": "",
    "GIUONG_2015": ""
  },
  {
    "STT": 18,
    "MA_KHOA": "K47",
    "TEN_KHOA": "Khoa Xét nghiệm",
    "BAN_KHAM": "",
    "GIUONG_PD": "",
    "GIUONG_TK": "",
    "GIUONG_HSTC": "",
    "GIUONG_HSCC": "",
    "TU_NGAY": "",
    "DEN_NGAY": "",
    "MA_CSKCB": 92114,
    "ID": 437164,
    "MA_LOAI_KCB": "",
    "LDLK": 2,
    "LIEN_KHOA": "",
    "GIUONG_2015": ""
  },
  {
    "STT": 19,
    "MA_KHOA": "10.20",
    "TEN_KHOA": "Ngoại thần kinh",
    "BAN_KHAM": 1,
    "GIUONG_PD": "",
    "GIUONG_TK": "",
    "GIUONG_HSTC": "",
    "GIUONG_HSCC": "",
    "TU_NGAY": "",
    "DEN_NGAY": "",
    "MA_CSKCB": 92114,
    "ID": 437170,
    "MA_LOAI_KCB": 1,
    "LDLK": 2,
    "LIEN_KHOA": "",
    "GIUONG_2015": ""
  },
  {
    "STT": 20,
    "MA_KHOA": "02.13",
    "TEN_KHOA": "Da liễu",
    "BAN_KHAM": 1,
    "GIUONG_PD": "",
    "GIUONG_TK": "",
    "GIUONG_HSTC": "",
    "GIUONG_HSCC": "",
    "TU_NGAY": "",
    "DEN_NGAY": "",
    "MA_CSKCB": 92114,
    "ID": 437171,
    "MA_LOAI_KCB": 1,
    "LDLK": 2,
    "LIEN_KHOA": "",
    "GIUONG_2015": ""
  },
  {
    "STT": 21,
    "MA_KHOA": "K44",
    "TEN_KHOA": "Khoa Dược",
    "BAN_KHAM": "",
    "GIUONG_PD": "",
    "GIUONG_TK": "",
    "GIUONG_HSTC": "",
    "GIUONG_HSCC": "",
    "TU_NGAY": "",
    "DEN_NGAY": "",
    "MA_CSKCB": 92114,
    "ID": 437172,
    "MA_LOAI_KCB": "",
    "LDLK": 2,
    "LIEN_KHOA": "",
    "GIUONG_2015": ""
  },
  {
    "STT": 22,
    "MA_KHOA": "02.04",
    "TEN_KHOA": "Nội Tim mạch",
    "BAN_KHAM": 2,
    "GIUONG_PD": "",
    "GIUONG_TK": "",
    "GIUONG_HSTC": "",
    "GIUONG_HSCC": "",
    "TU_NGAY": "",
    "DEN_NGAY": "",
    "MA_CSKCB": 92114,
    "ID": 437173,
    "MA_LOAI_KCB": 1,
    "LDLK": 2,
    "LIEN_KHOA": "",
    "GIUONG_2015": ""
  },
  {
    "STT": 23,
    "MA_KHOA": "10.24",
    "TEN_KHOA": "Chấn thương chỉnh hình",
    "BAN_KHAM": 2,
    "GIUONG_PD": "",
    "GIUONG_TK": "",
    "GIUONG_HSTC": "",
    "GIUONG_HSCC": "",
    "TU_NGAY": "",
    "DEN_NGAY": "",
    "MA_CSKCB": 92114,
    "ID": 437175,
    "MA_LOAI_KCB": 1,
    "LDLK": 2,
    "LIEN_KHOA": "",
    "GIUONG_2015": ""
  },
  {
    "STT": 24,
    "MA_KHOA": "K27",
    "TEN_KHOA": "Khoa Phụ sản",
    "BAN_KHAM": "",
    "GIUONG_PD": 25,
    "GIUONG_TK": 25,
    "GIUONG_HSTC": "",
    "GIUONG_HSCC": "",
    "TU_NGAY": "",
    "DEN_NGAY": "",
    "MA_CSKCB": 92114,
    "ID": 437176,
    "MA_LOAI_KCB": 4,
    "LDLK": 2,
    "LIEN_KHOA": "",
    "GIUONG_2015": ""
  },
  {
    "STT": 25,
    "MA_KHOA": "10.19",
    "TEN_KHOA": "Ngoại tổng hợp",
    "BAN_KHAM": 3,
    "GIUONG_PD": "",
    "GIUONG_TK": "",
    "GIUONG_HSTC": "",
    "GIUONG_HSCC": "",
    "TU_NGAY": "",
    "DEN_NGAY": "",
    "MA_CSKCB": 92114,
    "ID": 475580,
    "MA_LOAI_KCB": 1,
    "LDLK": 2,
    "LIEN_KHOA": "",
    "GIUONG_2015": ""
  },
  {
    "STT": 26,
    "MA_KHOA": "01.02",
    "TEN_KHOA": "Hồi sức cấp cứu và chống độc",
    "BAN_KHAM": 5,
    "GIUONG_PD": "",
    "GIUONG_TK": "",
    "GIUONG_HSTC": "",
    "GIUONG_HSCC": "",
    "TU_NGAY": "20240101",
    "DEN_NGAY": "",
    "MA_CSKCB": 92114,
    "ID": 524928,
    "MA_LOAI_KCB": "",
    "LDLK": "",
    "LIEN_KHOA": "",
    "GIUONG_2015": ""
  }
];
