/** AUTO-GENERATED from DuLieu_LUAT_DU_LIEU (12).xlsx + CV 302 ngưỡng LCS 01/7/2026 */
export const PHIEN_BAN_SEED_LUAT_DU_LIEU_MUC1 = '2026-06-11_cv302_xml_lcs';
export const COT_SEED_LUAT_DU_LIEU_MUC1 = ["TRANG_THAI","MA_LUAT","TEN_QUY_TAC","DIEU_KIEN","CANH_BAO","DIEU_KIEN (Toán tử No-Code)","GHI_CHU_SUA","NGUON_DU_LIEU"];
export const DU_LIEU_SEED_LUAT_DU_LIEU_MUC1 = [
  {
    "id": "SEED_DULIEU_1",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_01",
    "TEN_QUY_TAC": "BHYT không âm",
    "DIEU_KIEN": "NOT IS_EMPTY(XML1.T_BHTT) AND TO_NUMBER(XML1.T_BHTT) < 0",
    "CANH_BAO": "⛔ Tiền BHYT không hợp lệ",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_2",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_02",
    "TEN_QUY_TAC": "BHYT thanh toán vượt Tổng BV",
    "DIEU_KIEN": "!IS_EMPTY(XML1.T_BHTT) AND !IS_EMPTY(XML1.T_TONGCHI_BV) AND TO_NUMBER(XML1.T_BHTT) > TO_NUMBER(XML1.T_TONGCHI_BV)",
    "CANH_BAO": "⛔ Tiền BHYT chi trả lớn hơn cả tổng chi phí của đợt điều trị.",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_3",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_03",
    "TEN_QUY_TAC": "BN không âm",
    "DIEU_KIEN": "NOT IS_EMPTY(XML1.T_BNTT) AND TO_NUMBER(XML1.T_BNTT) < 0",
    "CANH_BAO": "⛔ Tiền BN không hợp lệ",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_4",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_04",
    "TEN_QUY_TAC": "Cân đối tổng chi BV",
    "DIEU_KIEN": "!IS_EMPTY(XML1.T_TONGCHI_BV) AND ABS(TO_NUMBER(XML1.T_TONGCHI_BV) - (TO_NUMBER(XML1.T_BHTT) + TO_NUMBER(XML1.T_BNCCT) + TO_NUMBER(XML1.T_BNTT) + TO_NUMBER(XML1.T_NGUONKHAC) + TO_NUMBER(XML1.T_NGOAIDS))) > 1",
    "CANH_BAO": "⛔ Tổng chi BV lệch với tổng các nguồn thanh toán (BHYT + CCT + BN tự trả + Nguồn khác + Ngoài DS HIV/AIDS).",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ [Rà soát] Math.abs→ABS",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_7",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_07",
    "TEN_QUY_TAC": "Cấp thuốc mạn tính < 20 ngày",
    "DIEU_KIEN": "XML1.MA_LOAI_KCB == '02' AND XML1.SO_NGAY_DTRI < 20",
    "CANH_BAO": "⚠️ Kiểm tra: Đợt thuốc mạn tính quá ngắn (dưới 20 ngày), yêu cầu giải trình lý do.",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_8",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_08",
    "TEN_QUY_TAC": "Cấp thuốc mạn tính quá 30 ngày",
    "DIEU_KIEN": "XML1.MA_LOAI_KCB == '1' AND COUNT_IF(XML2, item => item.MA_NHOM IN ('1','2') AND item.SO_NGAY > 30) > 0",
    "CANH_BAO": "⛔ BHYT: Kê đơn bệnh mạn tính thông thường không được quá 30 ngày (trừ đợt lễ/dịch).",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ Trùng lặp hoàn toàn với D85 (XML_074). Đã tách logic: D85 = ngoại trú (MA_LOAI_KCB='02'), D89 = cấp thuốc mạn tính ngoại trú qua XML2",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_10",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_10",
    "TEN_QUY_TAC": "Chuyển tuyến không ghi ngày hẹn",
    "DIEU_KIEN": "!IS_EMPTY(XML1.GIAY_CHUYEN_TUYEN) AND IS_EMPTY(XML1.NGAY_TAI_KHAM)",
    "CANH_BAO": "⚠️ Thiếu dữ liệu: Hồ sơ có giấy chuyển tuyến nhưng chưa ghi ngày tái khám theo XML1.",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ Thay trường không chuẩn MA_LYDO_VVIEN/NGAY_HEN bằng GIAY_CHUYEN_TUYEN/NGAY_TAI_KHAM theo schema XML1.",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_12",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_12",
    "TEN_QUY_TAC": "Có chi phí nhưng không có loại KCB",
    "DIEU_KIEN": "TO_NUMBER(XML1.T_TONGCHI_BV)>0 AND IS_EMPTY(XML1.MA_LOAI_KCB)",
    "CANH_BAO": "🧩 Sai logic: Thiếu loại KCB",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_13",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_13",
    "TEN_QUY_TAC": "Có dịch vụ nhưng tổng tiền = 0",
    "DIEU_KIEN": "COUNT(XML3) > 0 && XML1.T_TONGCHI_BV = 0",
    "CANH_BAO": "🔴 Có dịch vụ nhưng không phát sinh chi phí",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ [Rà soát] TONG_TIEN→T_TONGCHI_BV",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_14",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_14",
    "TEN_QUY_TAC": "Có DV nhưng thiếu ICD",
    "DIEU_KIEN": "(COUNT_IF(XML3,1=1)>0 OR COUNT_IF(XML2,1=1)>0) AND IS_EMPTY(XML1.MA_BENH_CHINH)",
    "CANH_BAO": "⛔ Xuất toán: Thiếu ICD chính",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_15",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_15",
    "TEN_QUY_TAC": "Có Điều trị nhưng Trống Chẩn đoán",
    "DIEU_KIEN": "IS_EMPTY(XML1.MA_BENH_CHINH) AND TO_NUMBER(XML1.T_TONGCHI_BV) > 0",
    "CANH_BAO": "⛔ Hồ sơ có tính tiền điều trị nhưng lại bỏ trống Mã Bệnh Chính (ICD-10).",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_16",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_16",
    "TEN_QUY_TAC": "Có KQ xét nghiệm nhưng thiếu ngày",
    "DIEU_KIEN": "COUNT_IF(XML4, item => !IS_EMPTY(item.GIA_TRI) AND IS_EMPTY(item.NGAY_KQ)) > 0",
    "CANH_BAO": "⛔ Lỗi XML4: Chỉ số xét nghiệm đã có kết quả nhưng bỏ trống thời gian thực hiện/trả kết quả.",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ Thêm 'item.' prefix cho GIA_TRI, NGAY_KQ trong lambda",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_17",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_17",
    "TEN_QUY_TAC": "Dịch vụ chỉ định sau khi ra viện",
    "DIEU_KIEN": "COUNT_IF(XML3, item => TO_NUMBER(item.NGAY_YL) > TO_NUMBER(XML1.NGAY_RA)) > 0",
    "CANH_BAO": "⛔ Logic thời gian: Ngày y lệnh dịch vụ phát sinh sau khi bệnh nhân đã làm thủ tục ra viện.",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ Thêm 'item =>' và 'item.' prefix trong COUNT_IF lambda",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_18",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_18",
    "TEN_QUY_TAC": "Chi phí KCB BHYT chỉ định/thực hiện ngoài thời gian điều trị",
    "DIEU_KIEN": "COUNT_IF(XML3, item => !IS_EMPTY(item.NGAY_YL) AND !IS_EMPTY(XML1.NGAY_VAO) AND !IS_EMPTY(XML1.NGAY_RA) AND (TO_NUMBER(item.NGAY_YL) < TO_NUMBER(XML1.NGAY_VAO) OR TO_NUMBER(item.NGAY_YL) > TO_NUMBER(XML1.NGAY_RA))) > 0",
    "CANH_BAO": "⛔ Kiểm tra chi phí: Có chi phí KCB BHYT được chỉ định/thực hiện ngoài thời gian nằm viện hoặc ngoài thời gian điều trị ngoại trú. Đối chiếu NGAY_YL với NGAY_VAO và NGAY_RA.",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ Bổ sung lambda item => và chuẩn hóa so sánh NGAY_YL với NGAY_VAO/NGAY_RA để kiểm tra chi phí ngoài thời gian điều trị.",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_19",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_19",
    "TEN_QUY_TAC": "Diễn biến rỗng (XML5)",
    "DIEU_KIEN": "XML1.MA_LOAI_KCB == '3' && (COUNT(XML5) == 0 || ALL(XML5, i => IS_EMPTY(i.DIEN_BIEN)))",
    "CANH_BAO": "⛔ [XUẤT TOÁN]: Bệnh nhân nội trú (Mã 3) nhưng không có dữ liệu diễn biến bệnh lý hàng ngày tại bảng XML5.",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ [Rà soát] .length→COUNT(); .every→ALL()",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_20",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_20",
    "TEN_QUY_TAC": "DVKT giá cao bất thường",
    "DIEU_KIEN": "COUNT_IF(XML3, item => TO_NUMBER(item.DON_GIA_BV) > 50000000) > 0",
    "CANH_BAO": "⚠️ Cảnh báo dịch vụ kỹ thuật hoặc VTYT có đơn giá vượt quá 50 triệu đồng.",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_22",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_22",
    "TEN_QUY_TAC": "DVKT thiếu ngày y lệnh",
    "DIEU_KIEN": "COUNT_IF(XML3, item => !IS_EMPTY(item.MA_DICH_VU) AND IS_EMPTY(item.NGAY_YL)) > 0",
    "CANH_BAO": "⚠️ Nguy hiểm: DVKT thiếu ngày",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ Chuẩn hóa COUNT_IF sang lambda item => để tránh truy cập biến trần ngoài ngữ cảnh dòng XML3.",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_23",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_23",
    "TEN_QUY_TAC": "DVKT tính tiền sai (SL x Giá)",
    "DIEU_KIEN": "COUNT_IF(XML3, item => !IS_EMPTY(item.THANH_TIEN_BV) AND ABS(TO_NUMBER(item.THANH_TIEN_BV) - (TO_NUMBER(item.SO_LUONG) * TO_NUMBER(item.DON_GIA_BV))) > 1) > 0",
    "CANH_BAO": "⛔ Có DVKT/VTYT tại XML3 tính sai công thức (Số lượng x Đơn giá BV).",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ [Rà soát] Math.abs→ABS",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_24",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_24",
    "TEN_QUY_TAC": "Điều trị ngoại trú quá 30 ngày",
    "DIEU_KIEN": "XML1.MA_LOAI_KCB == '02' AND XML1.SO_NGAY_DTRI > 30",
    "CANH_BAO": "⛔ Cảnh báo: Đợt điều trị ngoại trú thông thường không được vượt quá 30 ngày thuốc.",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_25",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_25",
    "TEN_QUY_TAC": "Đối soát Cân nặng & Thuốc",
    "DIEU_KIEN": "!IS_EMPTY(XML1.NGAY_SINH) && DIFF_DAYS(XML1.NGAY_SINH, XML1.NGAY_VAO) >= 0 && DIFF_DAYS(XML1.NGAY_SINH, XML1.NGAY_VAO) < 28 && TO_NUMBER(XML1.CAN_NANG) <= 0 && COUNT_IF(XML2, item => item.MA_NHOM IN ('4','5')) > 0",
    "CANH_BAO": "⛔ [LÂM SÀNG]: Hồ sơ sơ sinh có sử dụng thuốc nhưng bỏ trống thông tin Cân nặng (CAN_NANG) để tính liều.",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "[Sửa L25] Ngưỡng sơ sinh 30 → 28 ngày; thêm >= 0 tránh data lỗi; lọc chỉ nhóm thuốc (4,5) thay vì XML2.length > 0 | ✏️ [Rà soát] [].includes()→IN()",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_26",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_26",
    "TEN_QUY_TAC": "Đơn giá bằng 0",
    "DIEU_KIEN": "COUNT_IF(XML3, item => (!IS_EMPTY(item.DON_GIA_BV) AND TO_NUMBER(item.DON_GIA_BV) = 0) OR (!IS_EMPTY(item.DON_GIA_BH) AND TO_NUMBER(item.DON_GIA_BH) = 0)) > 0",
    "CANH_BAO": "❗ Đơn giá bằng 0",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ Bỏ DON_GIA không có trong XML3 chuẩn; chỉ kiểm tra DON_GIA_BV/DON_GIA_BH theo schema hiện hành.",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_27",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_27",
    "TEN_QUY_TAC": "Giá = 0 nhưng vẫn thanh toán",
    "DIEU_KIEN": "COUNT_IF(XML2, i => TO_NUMBER(i.DON_GIA) == 0 && TO_NUMBER(i.THANH_TIEN_BH) > 0) > 0",
    "CANH_BAO": "⚠️ Thuốc giá 0 nhưng vẫn được BHYT thanh toán",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_29",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_29",
    "TEN_QUY_TAC": "Giờ/Phút không hợp lệ",
    "DIEU_KIEN": "SUBSTR(XML1.NGAY_VAO, 9, 2) > '23' OR SUBSTR(XML1.NGAY_VAO, 11, 2) > '59' OR SUBSTR(XML1.NGAY_RA, 9, 2) > '23' OR SUBSTR(XML1.NGAY_RA, 11, 2) > '59'",
    "CANH_BAO": "⛔ [DỮ LIỆU]: Giá trị Giờ (>23) hoặc Phút (>59) không đúng quy chuẩn đồng hồ.",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ Bổ sung kiểm tra Giờ/Phút của NGAY_RA (trước đó chỉ check NGAY_VAO)",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_32",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_32",
    "TEN_QUY_TAC": "Hồ sơ rỗng không Dịch vụ",
    "DIEU_KIEN": "COUNT(XML2) == 0 AND COUNT(XML3) == 0",
    "CANH_BAO": "⚠️ Hồ sơ chỉ có hành chính, không hề phát sinh bất cứ thuốc hay DVKT nào.",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ [Rà soát] .length→COUNT()",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_33",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_33",
    "TEN_QUY_TAC": "Hồ sơ Thiếu XML1",
    "DIEU_KIEN": "IS_EMPTY(XML1.MA_LK)",
    "CANH_BAO": "⛔ Lỗi nghiêm trọng: Tệp dữ liệu thiếu bảng tổng hợp XML1.",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_34",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_34",
    "TEN_QUY_TAC": "ICD kèm không có ICD chính",
    "DIEU_KIEN": "NOT IS_EMPTY(XML1.MA_BENH_KT) AND IS_EMPTY(XML1.MA_BENH_CHINH)",
    "CANH_BAO": "🧩 Sai logic: ICD kèm không có ICD chính",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_35",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_35",
    "TEN_QUY_TAC": "ICD quá ngắn",
    "DIEU_KIEN": "NOT IS_EMPTY(XML1.MA_BENH_CHINH) AND LEN(XML1.MA_BENH_CHINH) < 3",
    "CANH_BAO": "🔎 Cảnh báo: ICD không hợp lệ",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_36",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_36",
    "TEN_QUY_TAC": "Kết quả CLS trả về sau khi ra viện",
    "DIEU_KIEN": "COUNT_IF(XML4, item => !IS_EMPTY(item.NGAY_KQ) AND !IS_EMPTY(XML1.NGAY_RA) AND TO_NUMBER(item.NGAY_KQ) > TO_NUMBER(XML1.NGAY_RA)) > 0",
    "CANH_BAO": "⛔ Lỗi quy trình: Thời điểm trả kết quả xét nghiệm phát sinh sau khi bệnh nhân đã ra viện.",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ Đổi truy cập XML4.NGAY_KQ kiểu tập hợp sang COUNT_IF theo từng dòng XML4 để tương thích engine.",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_37",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_37",
    "TEN_QUY_TAC": "Kết quả sau khi ra viện",
    "DIEU_KIEN": "XML1.MA_LOAI_KCB IN ('2','3') AND COUNT_IF(XML3, item => !IS_EMPTY(item.NGAY_KQ) AND !IS_EMPTY(XML1.NGAY_RA) AND TO_NUMBER(item.NGAY_KQ) > TO_NUMBER(XML1.NGAY_RA)) > 0",
    "CANH_BAO": "⛔ [XUẤT TOÁN]: Bệnh nhân đã ra viện nhưng sau đó mới có kết quả CLS phục vụ điều trị.",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ Chuẩn hóa XML3 từ truy cập trực tiếp sang COUNT_IF theo từng dòng để tránh lỗi row-vs-collection.",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_38",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_38",
    "TEN_QUY_TAC": "Kết quả trước y lệnh",
    "DIEU_KIEN": "COUNT_IF(XML3, item => !IS_EMPTY(item.NGAY_KQ) AND !IS_EMPTY(item.NGAY_YL) AND TO_NUMBER((LEN(item.NGAY_KQ) == 8 ? item.NGAY_KQ + '0000' : (LEN(item.NGAY_KQ) == 10 ? item.NGAY_KQ + '00' : SUBSTR(item.NGAY_KQ, 1, 12)))) < TO_NUMBER((LEN(item.NGAY_YL) == 8 ? item.NGAY_YL + '0000' : (LEN(item.NGAY_YL) == 10 ? item.NGAY_YL + '00' : SUBSTR(item.NGAY_YL, 1, 12))))) > 0",
    "CANH_BAO": "❌ [LOGIC]: Thời điểm trả kết quả CLS diễn ra trước khi có y lệnh chỉ định.",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ Loại CASE WHEN/LENGTH không được engine hỗ trợ, thay bằng biểu thức ternary + LEN để chuẩn hóa NGAY_KQ/NGAY_YL về 12 ký tự.",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_39",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_39",
    "TEN_QUY_TAC": "Kết quả XN rỗng (XML4)",
    "DIEU_KIEN": "COUNT_IF(XML3, item => item.MA_NHOM NOT IN ('13','14')) > 0 && COUNT(XML4) == 0",
    "CANH_BAO": "⚠️ [THIẾU DỮ LIỆU]: Có chỉ định xét nghiệm (Nhóm 1) nhưng bảng XML4 không có kết quả chi tiết chỉ số.",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ [Rà soát] Tách mã PC_130_L27→L27b (KQ XN rỗng, khác ý nghĩa với Trống ngày KQ)",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_40",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_40",
    "TEN_QUY_TAC": "Khác Mã Liên kết (XML2)",
    "DIEU_KIEN": "COUNT_IF(XML2, item => !IS_EMPTY(item.MA_LK) AND item.MA_LK != XML1.MA_LK) > 0",
    "CANH_BAO": "⛔ Dữ liệu thuốc (XML2) có chứa Mã liên kết không khớp với XML1.",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ Thay ký pháp tập hợp DISTINCT/⊆ không được hỗ trợ bằng kiểm tra trực tiếp từng dòng XML2.",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_41",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_41",
    "TEN_QUY_TAC": "Khám ngoài hạn thẻ",
    "DIEU_KIEN": "NOT IS_EMPTY(XML1.GT_THE_TU) AND (TO_NUMBER(XML1.NGAY_VAO) < TO_NUMBER(XML1.GT_THE_TU) OR TO_NUMBER(XML1.NGAY_VAO) > TO_NUMBER(XML1.GT_THE_DEN))",
    "CANH_BAO": "⛔ Xuất toán: Khám ngoài hạn thẻ BHYT",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_42",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_42",
    "TEN_QUY_TAC": "Không chi phí nhưng có Dịch vụ",
    "DIEU_KIEN": "TO_NUMBER(XML1.T_TONGCHI_BV) == 0 AND (COUNT(XML2) > 0 OR COUNT(XML3) > 0)",
    "CANH_BAO": "⛔ Hồ sơ có kê thuốc/dịch vụ chi tiết nhưng Tổng chi phí báo cáo lại bằng 0.",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ [Rà soát] .length→COUNT()",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_43",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_43",
    "TEN_QUY_TAC": "Không có chi phí nhưng vẫn thanh toán",
    "DIEU_KIEN": "TO_NUMBER(XML1.T_TONGCHI_BV) = 0 AND TO_NUMBER(XML1.T_BHTT) > 0",
    "CANH_BAO": "⛔ Không có chi phí nhưng vẫn đề nghị thanh toán",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ [Rà soát] T_TONGCHI→T_TONGCHI_BV; Tách mã PC_130_L25→FIN_05",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_44",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_44",
    "TEN_QUY_TAC": "Không có dịch vụ nhưng có chi phí",
    "DIEU_KIEN": "COUNT(XML3) = 0 && XML1.T_TONGCHI_BV > 0",
    "CANH_BAO": "🔴 Có chi phí nhưng không có dịch vụ",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ [Rà soát] TONG_TIEN→T_TONGCHI_BV",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_45",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_45",
    "TEN_QUY_TAC": "Không có thẻ BHYT",
    "DIEU_KIEN": "IS_EMPTY(XML1.MA_THE_BHYT) AND TO_NUMBER(XML1.T_BHTT)>0",
    "CANH_BAO": "⛔ Xuất toán: Không có thẻ BHYT",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_46",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_46",
    "TEN_QUY_TAC": "Kiểm tra độ dài Ngày giờ",
    "DIEU_KIEN": "LEN(XML1.NGAY_VAO) != 12 OR LEN(XML1.NGAY_RA) != 12",
    "CANH_BAO": "⛔ [ĐẶC TẢ]: Ngày giờ phải đúng 12 ký tự (YYYYMMDDHHmm) theo QĐ 130.",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_47",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_47",
    "TEN_QUY_TAC": "Kiểm tra tỷ lệ hưởng 80%",
    "DIEU_KIEN": "SUBSTR(XML1.MA_THE_BHYT, 3, 1) == '4' && ((SUBSTR(XML1.NGAY_VAO, 1, 8) < '20260701' AND TO_NUMBER(XML1.T_TONGCHI_BH) >= 351000) OR (SUBSTR(XML1.NGAY_VAO, 1, 8) >= '20260701' AND TO_NUMBER(XML1.T_TONGCHI_BH) >= 379500)) && ABS(TO_NUMBER(XML1.T_BNCCT) - (TO_NUMBER(XML1.T_TONGCHI_BH) * 0.20)) > 10",
    "CANH_BAO": "⚠️ [KẾ TOÁN]: Thẻ mức 4 (hưởng 80%) nhưng số tiền Cùng chi trả lệch quá 10đ so với công thức 20% (ngưỡng miễn CCT 15% LCS: 351.000đ / 379.500đ).",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ [Rà soát] Math.abs→ABS",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_48",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_48",
    "TEN_QUY_TAC": "Kiểm tra tỷ lệ hưởng 95%",
    "DIEU_KIEN": "SUBSTR(XML1.MA_THE_BHYT, 3, 1) == '3' && ((SUBSTR(XML1.NGAY_VAO, 1, 8) < '20260701' AND TO_NUMBER(XML1.T_TONGCHI_BH) >= 351000) OR (SUBSTR(XML1.NGAY_VAO, 1, 8) >= '20260701' AND TO_NUMBER(XML1.T_TONGCHI_BH) >= 379500)) && ABS(TO_NUMBER(XML1.T_BNCCT) - (TO_NUMBER(XML1.T_TONGCHI_BH) * 0.05)) > 10",
    "CANH_BAO": "⚠️ [KẾ TOÁN]: Thẻ mức 3 (hưởng 95%) nhưng số tiền Cùng chi trả lệch quá 10đ so với công thức 5% (ngưỡng miễn CCT 15% LCS: 351.000đ / 379.500đ).",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ [Rà soát] Math.abs→ABS",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_49",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_49",
    "TEN_QUY_TAC": "Lệch BHYT trả (T_BHTT)",
    "DIEU_KIEN": "ABS(TO_NUMBER(XML1.T_BHTT) - (SUM_IF(XML2, item => !IS_EMPTY(item.T_BHTT), item => TO_NUMBER(item.T_BHTT)) + SUM_IF(XML3, item => !IS_EMPTY(item.T_BHTT), item => TO_NUMBER(item.T_BHTT)))) > 1",
    "CANH_BAO": "⛔ [KẾ TOÁN]: Tổng tiền quỹ BHYT thanh toán tại XML1 lệch với cộng dồn chi tiết XML2 và XML3.",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ Chuyển .reduce() sang SUM_IF để engine luật động tính được tổng chi tiết BHYT ở XML2/XML3.",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_50",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_50",
    "TEN_QUY_TAC": "Lệch thông tin báo cáo Thuốc",
    "DIEU_KIEN": "COUNT(XML2) > 0 AND TO_NUMBER(XML1.T_THUOC) == 0",
    "CANH_BAO": "⛔ Có phát sinh chi tiết Thuốc tại XML2 nhưng bảng XML1 không báo cáo tiền thuốc.",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ [Rà soát] .length→COUNT()",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_53",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_53",
    "TEN_QUY_TAC": "Lệch T_THUOC (XML1) vs tổng tiền BHYT chi tiết thuốc XML2",
    "DIEU_KIEN": "ABS(SUM_IF(XML2, item => item.MA_NHOM IN ('4','5'), item => !IS_EMPTY(item.THANH_TIEN_BH) ? TO_NUMBER(item.THANH_TIEN_BH) : (!IS_EMPTY(item.THANH_TIEN) ? TO_NUMBER(item.THANH_TIEN) : (!IS_EMPTY(item.THANH_TIEN_BV) ? TO_NUMBER(item.THANH_TIEN_BV) : TO_NUMBER(item.T_BHTT)))) - TO_NUMBER(XML1.T_THUOC)) > 1",
    "CANH_BAO": "⛔ [KẾ TOÁN]: Tổng tiền thuốc do BHYT thanh toán cộng dồn tại XML2 (ưu tiên THANH_TIEN_BH → THANH_TIEN → THANH_TIEN_BV → T_BHTT trên dòng; nhóm MA_NHOM 4,5) lệch so với T_THUOC tại XML1 (|chênh| > 1đ).",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ Không đối chiếu THANH_TIEN_BV (BV) với T_THUOC khi nghiệp vụ là đồng bộ phần BHYT: cùng thứ tự lấy tiền dòng như CLN-CHI-01. ABS hai chiều, ngưỡng >1đ, nhóm 4–5.",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_54",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_54",
    "TEN_QUY_TAC": "Lệch tiền VTYT (T_VTYT)",
    "DIEU_KIEN": "ABS(TO_NUMBER(XML1.T_VTYT) - SUM_IF(XML3, item => !IS_EMPTY(item.MA_VAT_TU) AND !IS_EMPTY(item.THANH_TIEN_BV), item => TO_NUMBER(item.THANH_TIEN_BV))) > 1",
    "CANH_BAO": "⛔ [KẾ TOÁN]: Tổng tiền VTYT tại XML1 không khớp với chi tiết các dòng Vật tư tại XML3.",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ Chỉ đối chiếu T_VTYT với các dòng XML3 có mã vật tư thực sự; không cộng nhầm giường/DVKT/xét nghiệm.",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_55",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_55",
    "TEN_QUY_TAC": "Mã khoa không thống nhất (Nội trú)",
    "DIEU_KIEN": "XML1.MA_LOAI_KCB == '3' && COUNT_IF(XML2, item => !IS_EMPTY(item.MA_KHOA) && item.MA_KHOA != XML1.MA_KHOA) > 0",
    "CANH_BAO": "⚠️ [KIỂM TRA]: Có thuốc kê tại khoa khác với khoa ra viện. (Cảnh báo để bác sĩ rà soát luồng chuyển khoa).",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_56",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_56",
    "TEN_QUY_TAC": "Mâu thuẫn ngày vào viện và tiếp đón",
    "DIEU_KIEN": "XML1.MA_LOAI_KCB == '2' AND TO_NUMBER(SUBSTR(XML1.NGAY_VAO, 1, 12)) < TO_NUMBER(SUBSTR(XML1.NGAY_VAO_NOI_TRU, 1, 12))",
    "CANH_BAO": "⛔ Lỗi logic: Thời điểm vào khoa nội trú không được trước thời điểm tiếp đón ngoại trú.",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ Sửa trường: NGAY_TIEP_DON không có trong XML1 QĐ 130. Thay bằng NGAY_VAO_NOI_TRU (trường đúng cho so sánh nhập viện)",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_57",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_57",
    "TEN_QUY_TAC": "Miễn Cùng chi trả (15% LCS)",
    "DIEU_KIEN": "((SUBSTR(XML1.NGAY_VAO, 1, 8) < '20260701' AND TO_NUMBER(XML1.T_TONGCHI_BH) < 351000) OR (SUBSTR(XML1.NGAY_VAO, 1, 8) >= '20260701' AND TO_NUMBER(XML1.T_TONGCHI_BH) < 379500)) && TO_NUMBER(XML1.T_BNCCT) > 0",
    "CANH_BAO": "⛔ [XUẤT TOÁN]: Tổng chi phí BHYT dưới 15% LCS (351.000đ trước 01/7/2026; 379.500đ từ 01/7/2026), người bệnh phải được hưởng 100% (BNCCT = 0).",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_59",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_59",
    "TEN_QUY_TAC": "Năm/Tháng/Ngày không hợp lệ",
    "DIEU_KIEN": "SUBSTR(XML1.NGAY_VAO, 1, 4) < '2024' OR SUBSTR(XML1.NGAY_VAO, 5, 2) < '01' OR SUBSTR(XML1.NGAY_VAO, 5, 2) > '12' OR SUBSTR(XML1.NGAY_VAO, 7, 2) < '01' OR SUBSTR(XML1.NGAY_VAO, 7, 2) > '31' OR SUBSTR(XML1.NGAY_RA, 1, 4) < '2024' OR SUBSTR(XML1.NGAY_RA, 5, 2) < '01' OR SUBSTR(XML1.NGAY_RA, 5, 2) > '12' OR SUBSTR(XML1.NGAY_RA, 7, 2) < '01' OR SUBSTR(XML1.NGAY_RA, 7, 2) > '31'",
    "CANH_BAO": "⛔ [DỮ LIỆU]: Chuỗi ngày vào viện không hợp lệ về mặt lịch pháp.",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ Loại BETWEEN không được engine hỗ trợ, thay bằng các so sánh cận trên/cận dưới tương đương cho tháng/ngày.",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_60",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_60",
    "TEN_QUY_TAC": "Ngày kết quả có trước Ngày y lệnh",
    "DIEU_KIEN": "COUNT_IF(XML3, item => !IS_EMPTY(item.NGAY_KQ) AND TO_NUMBER(item.NGAY_KQ) < TO_NUMBER(item.NGAY_YL)) > 0",
    "CANH_BAO": "⛔ Lỗi logic: Ngày trả kết quả dịch vụ (NGAY_KQ) không thể xảy ra trước ngày ra y lệnh (NGAY_YL).",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ Thêm 'item.' prefix cho NGAY_KQ, NGAY_YL trong lambda",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_62",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_62",
    "TEN_QUY_TAC": "NGAY_RA < NGAY_VAO",
    "DIEU_KIEN": "!IS_EMPTY(XML1.NGAY_RA) AND TO_NUMBER(XML1.NGAY_RA) < TO_NUMBER(XML1.NGAY_VAO)",
    "CANH_BAO": "🧩 Sai logic: Ngày ra trước ngày vào",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ Giữ một rule duy nhất cho kiểm tra NGAY_RA < NGAY_VAO và bổ sung chặn NGAY_RA rỗng để giảm dương tính giả.",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_64",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_64",
    "TEN_QUY_TAC": "NGAY_YL trước NGAY_VAO",
    "DIEU_KIEN": "COUNT_IF(XML3, item => TO_NUMBER(item.NGAY_YL) < TO_NUMBER(XML1.NGAY_VAO)) > 0",
    "CANH_BAO": "⛔ Kiểm tra chi phí: Có chỉ định dịch vụ trước thời điểm bắt đầu đợt KCB BHYT (NGAY_VAO).",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ Chuẩn hóa cảnh báo để tách rõ trường hợp NGAY_YL trước NGAY_VAO khỏi rule tổng quát XML_18.",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_66",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_66",
    "TEN_QUY_TAC": "Người lớn thiếu số CCCD/Định danh",
    "DIEU_KIEN": "(DATEDIFF_YEAR(SUBSTR(XML1.NGAY_SINH, 1, 8), SUBSTR(XML1.NGAY_VAO, 1, 8)) >= 14) AND IS_EMPTY(XML1.SO_CCCD)",
    "CANH_BAO": "⚠️ Cảnh báo: Bệnh nhân từ 14 tuổi trở lên bắt buộc phải có Số CCCD hoặc Mã định danh cá nhân.",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_67",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_67",
    "TEN_QUY_TAC": "Nhiều DV bất thường",
    "DIEU_KIEN": "COUNT_IF(XML3,1=1) > 20",
    "CANH_BAO": "🔎 Cảnh báo: Số lượng DVKT cao",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_68",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_68",
    "TEN_QUY_TAC": "Nội suy số ngày Giường",
    "DIEU_KIEN": "COUNT_IF(XML3, item => item.MA_NHOM == '14' AND TO_NUMBER(item.SO_LUONG) > ((XML1.KET_QUA_DTRI == '5' OR XML1.MA_LOAI_RV == '2') ? (DIFF_DAYS(XML1.NGAY_VAO, XML1.NGAY_RA) + 1) : DIFF_DAYS(XML1.NGAY_VAO, XML1.NGAY_RA))) > 0",
    "CANH_BAO": "⛔ [NỘI SUY]: Số lượng ngày giường vượt quá quy định tại Thông tư 39/2024/TT-BYT (Ngày ra - Ngày vào [+1 tùy TH]).",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ Đổi XML3 từ truy cập trực tiếp sang COUNT_IF theo từng dòng giường để nội suy số ngày nằm đúng ngữ nghĩa bảng chi tiết.",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_69",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_69",
    "TEN_QUY_TAC": "Oxy y tế vượt quá ngày nằm viện",
    "DIEU_KIEN": "SUM_IF(XML3, item => item.MA_NHOM == '15', item.SO_LUONG) > (DATEDIFF_MINUTE(XML1.NGAY_VAO, XML1.NGAY_RA))",
    "CANH_BAO": "⛔ Lỗi logic: Tổng thời gian sử dụng Oxy (phút) lớn hơn tổng thời gian nằm viện thực tế.",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ Sửa hàm: SUM_VOL(XML3.OXY) → SUM_IF với MA_NHOM='15' (oxy y tế). Đơn vị: phút so với phút nằm viện",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_70",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_70",
    "TEN_QUY_TAC": "Phát hiện Tiền Âm",
    "DIEU_KIEN": "TO_NUMBER(XML1.T_TONGCHI_BV) < 0 OR TO_NUMBER(XML1.T_BHTT) < 0 OR TO_NUMBER(XML1.T_BNTT) < 0",
    "CANH_BAO": "⛔ Trường dữ liệu tài chính mang số âm không hợp lệ.",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_71",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_71",
    "TEN_QUY_TAC": "Phẫu thuật loại ĐB vs Hồi sức",
    "DIEU_KIEN": "COUNT_IF(XML3, item => item.MA_PTTT_QT == '0') > 0 && COUNT_IF(XML3, item => item.MA_NHOM == '14' && CONTAINS(item.TEN_DICH_VU, 'Hồi sức')) == 0",
    "CANH_BAO": "⚠️ [QUAN TRỌNG]: Phẫu thuật loại Đặc biệt nhưng không có y lệnh tiền giường Hồi sức tích cực đi kèm.",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ [Rà soát] .includes→CONTAINS()",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_72",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_72",
    "TEN_QUY_TAC": "Quá nhiều DVKT trong thời gian ngắn",
    "DIEU_KIEN": "COUNT(XML3) > 20 AND !IS_EMPTY(XML1.NGAY_VAO) AND !IS_EMPTY(XML1.NGAY_RA) AND DIFF_HOURS(XML1.NGAY_VAO, XML1.NGAY_RA) < 2",
    "CANH_BAO": "⚠️ Bệnh nhân nằm viện dưới 2 giờ đồng hồ nhưng phát sinh hơn 20 loại DVKT.",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ [Rà soát] .length→COUNT()",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_73",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_73",
    "TEN_QUY_TAC": "Sai định dạng ngày",
    "DIEU_KIEN": "COUNT_IF(XML3, item => (!IS_EMPTY(item.NGAY_KQ) AND LEN(item.NGAY_KQ) != 12) OR (!IS_EMPTY(item.NGAY_YL) AND LEN(item.NGAY_YL) != 12)) > 0",
    "CANH_BAO": "❗ Sai định dạng YYYYMMDDHHMM",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ Thay MATCH_REGEX không có trong engine bằng kiểm tra độ dài 12 ký tự cho các trường thời gian dạng YYYYMMDDHHMM.",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_74",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_74",
    "TEN_QUY_TAC": "Sai mã thẻ BHYT học sinh/sinh viên",
    "DIEU_KIEN": "STARTS_WITH(XML1.MA_THE_BHYT, 'HS') AND DATEDIFF_YEAR(SUBSTR(XML1.NGAY_SINH, 1, 8), SUBSTR(XML1.NGAY_VAO, 1, 8)) > 25",
    "CANH_BAO": "⚠️ Logic: Thẻ BHYT học sinh (HS) nhưng bệnh nhân trên 25 tuổi, yêu cầu kiểm tra lại đối tượng.",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ Sửa CURRENT_DATE (không rõ) → dùng NGAY_VAO. Thêm SUBSTR cho NGAY_SINH (8 ký tự) | ✏️ [Rà soát] MA_THE→MA_THE_BHYT",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_75",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_75",
    "TEN_QUY_TAC": "Số lượng bất thường",
    "DIEU_KIEN": "COUNT_IF(XML3, item => TO_NUMBER(item.SO_LUONG) > 50) > 0",
    "CANH_BAO": "⚠️ Số lượng dịch vụ bất thường",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_76",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_76",
    "TEN_QUY_TAC": "Số lượng thuốc bất thường",
    "DIEU_KIEN": "COUNT_IF(XML2, item => TO_NUMBER(item.SO_LUONG) > 100 AND !IS_EMPTY(item.MA_THUOC)) > 0",
    "CANH_BAO": "⚠️ Phát hiện thuốc kê với số lượng cực lớn (>100). Đề nghị kiểm tra đơn vị tính.",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_77",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_77",
    "TEN_QUY_TAC": "Số ngày điều trị = 0",
    "DIEU_KIEN": "XML1.MA_LOAI_KCB IN ('2','3') AND SUBSTR(XML1.NGAY_RA, 1, 8) == SUBSTR(XML1.NGAY_VAO, 1, 8) AND XML1.SO_NGAY_DTRI == 0",
    "CANH_BAO": "⚠️ Thời gian điều trị bất thường",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ Bổ sung điều kiện MA_LOAI_KCB nội trú/ban ngày + SO_NGAY_DTRI=0 (ngoại trú vào-ra cùng ngày là bình thường)",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_78",
    "TRANG_THAI": "OFF",
    "MA_LUAT": "XML_78",
    "TEN_QUY_TAC": "Sơ sinh vs Giấy chứng sinh",
    "DIEU_KIEN": "1 == 0",
    "CANH_BAO": "⛔ [QUAN TRỌNG]: Trẻ chưa có thẻ BHYT (dùng thẻ mẹ) nhưng thiếu dữ liệu Giấy chứng sinh điện tử (XML14).",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ [Production review] Vô hiệu hóa trước deploy: tham chiếu XML14 ngoài phạm vi payload XML1-XML6 đang dùng trong engine hiện tại. Điều kiện gốc: !IS_EMPTY(XML1.MA_THE_BHYT) && STARTS_WITH(XML1.MA_THE_BHYT, 'TE') && DIFF_DAYS(XML1.NGAY_SINH, XML1.NGAY_VAO) < 60 && COUNT(XML14) == 0",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_79",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_79",
    "TEN_QUY_TAC": "Thành tiền sai lệch",
    "DIEU_KIEN": "COUNT_IF(XML3, item => TO_NUMBER(item.SO_LUONG) * TO_NUMBER(item.DON_GIA_BV) <> TO_NUMBER(item.THANH_TIEN_BV)) > 0",
    "CANH_BAO": "🔴 Sai lệch thành tiền",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ [Rà soát] THANH_TIEN→THANH_TIEN_BV và DON_GIA→DON_GIA_BV theo schema XML3 hiện hành.",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_80",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_80",
    "TEN_QUY_TAC": "Thanh toán trước khi ra viện",
    "DIEU_KIEN": "!IS_EMPTY(XML1.NGAY_TTOAN) && !IS_EMPTY(XML1.NGAY_RA) && TO_NUMBER(XML1.NGAY_TTOAN) < TO_NUMBER(XML1.NGAY_RA)",
    "CANH_BAO": "⛔ [LOGIC]: Ngày thanh toán (NGAY_TTOAN) không được phép trước thời điểm bệnh nhân ra viện.",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_81",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_81",
    "TEN_QUY_TAC": "Thẻ mức 1, 2, 5 phải hưởng 100%",
    "DIEU_KIEN": "SUBSTR(XML1.MA_THE_BHYT, 3, 1) IN ('1','2','5') && TO_NUMBER(XML1.T_BNCCT) > 0",
    "CANH_BAO": "⛔ [SAI QUYỀN LỢI]: Đối tượng mức 1,2,5 phải hưởng 100% BHYT, nhưng hồ sơ đang thu tiền Cùng chi trả.",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ [Rà soát] [].includes()→IN()",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_82",
    "TRANG_THAI": "OFF",
    "MA_LUAT": "XML_82",
    "TEN_QUY_TAC": "Thiếu hồ sơ sơ sinh (XML8)",
    "DIEU_KIEN": "1 == 0",
    "CANH_BAO": "⚠️ [DỮ LIỆU]: Trẻ sơ sinh điều trị nội trú thiếu bảng tóm tắt hồ sơ bệnh án sơ sinh (XML8).",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ [Production review] Vô hiệu hóa trước deploy: tham chiếu XML8 ngoài phạm vi payload XML1-XML6 đang dùng trong engine hiện tại. Điều kiện gốc: !IS_EMPTY(XML1.NGAY_SINH) && DIFF_DAYS(XML1.NGAY_SINH, XML1.NGAY_VAO) < 30 && XML1.MA_LOAI_KCB == '3' && COUNT(XML8) == 0",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_83",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_83",
    "TEN_QUY_TAC": "Thiếu mã dịch vụ",
    "DIEU_KIEN": "COUNT_IF(XML3, item => IS_EMPTY(item.MA_DICH_VU)) > 0",
    "CANH_BAO": "❗ Thiếu mã dịch vụ",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ [Rà soát] MA_DV→MA_DICH_VU",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_84",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_84",
    "TEN_QUY_TAC": "Thiếu mã khoa điều trị",
    "DIEU_KIEN": "IS_EMPTY(XML1.MA_KHOA)",
    "CANH_BAO": "❗ Thiếu khoa điều trị",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_85",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_85",
    "TEN_QUY_TAC": "Thiếu thông tin bác sĩ chỉ định",
    "DIEU_KIEN": "COUNT_IF(XML3, item => IS_EMPTY(item.MA_BAC_SI)) > 0",
    "CANH_BAO": "❗ Thiếu bác sĩ chỉ định",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_86",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_86",
    "TEN_QUY_TAC": "Thiếu trường bắt buộc trong XML2",
    "DIEU_KIEN": "COUNT_IF(XML2, item => IS_EMPTY(item.MA_THUOC) || IS_EMPTY(item.TEN_THUOC) || IS_EMPTY(item.MA_NHOM) || IS_EMPTY(item.SO_LUONG) || IS_EMPTY(item.DON_GIA) || IS_EMPTY(item.MA_KHOA) || IS_EMPTY(item.MA_BAC_SI) || IS_EMPTY(item.NGAY_YL)) > 0",
    "CANH_BAO": "❗ Thiếu trường bắt buộc XML2",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_87",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_87",
    "TEN_QUY_TAC": "Thiếu trường bắt buộc trong XML3",
    "DIEU_KIEN": "COUNT_IF(XML3, item => (IS_EMPTY(item.MA_DICH_VU) AND IS_EMPTY(item.MA_VAT_TU)) || IS_EMPTY(item.SO_LUONG) || (IS_EMPTY(item.DON_GIA_BV) AND IS_EMPTY(item.DON_GIA_BH)) || IS_EMPTY(item.MA_KHOA) || IS_EMPTY(item.MA_BAC_SI) || IS_EMPTY(item.NGAY_YL)) > 0",
    "CANH_BAO": "❗ Thiếu trường bắt buộc XML3",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ [Rà soát] MA_DV→MA_DICH_VU và bỏ DON_GIA không có trong XML3 chuẩn, chỉ giữ DON_GIA_BV/DON_GIA_BH.",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_88",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_88",
    "TEN_QUY_TAC": "Thiếu XML2 nhưng có tiền thuốc",
    "DIEU_KIEN": "COUNT(XML2) == 0 AND TO_NUMBER(XML1.T_THUOC) > 0",
    "CANH_BAO": "⚠️ Có tiền thuốc nhưng không có XML2",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ Đổi SUM không được hỗ trợ sang kiểm tra thiếu hoàn toàn XML2 để bám đúng ý nghĩa của rule.",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_90",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_90",
    "TEN_QUY_TAC": "Thời gian phẫu thuật logic",
    "DIEU_KIEN": "COUNT_IF(XML3, item => item.MA_NHOM == '8' AND !IS_EMPTY(item.NGAY_YL) AND !IS_EMPTY(item.NGAY_KQ) AND (DIFF_HOURS(item.NGAY_YL, item.NGAY_KQ) * 60) < 15) > 0",
    "CANH_BAO": "⚠️ [CẢNH BÁO]: Thời gian phẫu thuật quá ngắn (<15 phút). Kiểm tra lại tính xác thực của ca mổ.",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ Đổi XML3 từ truy cập trực tiếp sang COUNT_IF theo từng dòng phẫu thuật để rule thực thi đúng trên danh sách dịch vụ.",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_91",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_91",
    "TEN_QUY_TAC": "Thuốc độc/Gây nghiện vs Tuổi",
    "DIEU_KIEN": "COUNT_IF(XML2, item => item.MA_NHOM IN ('10','11')) > 0 AND DATEDIFF_DAY(SUBSTR(XML1.NGAY_SINH, 1, 8), SUBSTR(XML1.NGAY_VAO, 1, 8)) < 365",
    "CANH_BAO": "❌ [NGUY HIỂM]: Chỉ định thuốc gây nghiện cho trẻ em dưới 1 tuổi. Yêu cầu hội chẩn.",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ Chuẩn hóa XML2 sang COUNT_IF theo từng dòng, đồng thời giữ điều kiện tuổi < 1 năm dựa trên NGAY_SINH/NGAY_VAO.",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_92",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_92",
    "TEN_QUY_TAC": "Thuốc kê sau ngày ra viện",
    "DIEU_KIEN": "COUNT_IF(XML2, item => TO_NUMBER(item.NGAY_YL) > TO_NUMBER(XML1.NGAY_RA)) > 0",
    "CANH_BAO": "⛔ Logic thời gian: Ngày y lệnh thuốc (NGAY_YL) phát sinh sau thời điểm bệnh nhân đã ra viện.",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ Thêm 'item =>' và 'item.' prefix trong COUNT_IF lambda",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_93",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_93",
    "TEN_QUY_TAC": "Thuốc kê trước ngày vào viện",
    "DIEU_KIEN": "COUNT_IF(XML2, item => TO_NUMBER(item.NGAY_YL) < TO_NUMBER(XML1.NGAY_VAO)) > 0",
    "CANH_BAO": "⛔ Logic thời gian: Ngày y lệnh thuốc (NGAY_YL) diễn ra trước thời điểm bệnh nhân nhập viện.",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ Thêm 'item =>' và 'item.' prefix trong COUNT_IF lambda",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_95",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_95",
    "TEN_QUY_TAC": "Thuốc không có số lượng",
    "DIEU_KIEN": "COUNT_IF(XML2, item => TO_NUMBER(item.SO_LUONG) = 0 AND NOT IS_EMPTY(item.MA_THUOC)) > 0",
    "CANH_BAO": "⚠️ Nguy hiểm: Thuốc số lượng = 0",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ Bổ sung lambda item => để COUNT_IF đọc đúng SO_LUONG/MA_THUOC theo từng dòng XML2.",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_96",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_96",
    "TEN_QUY_TAC": "Thuốc ngoài khoảng thời gian điều trị",
    "DIEU_KIEN": "COUNT_IF(XML2, item => !IS_EMPTY(item.NGAY_YL) AND !IS_EMPTY(XML1.NGAY_VAO) AND !IS_EMPTY(XML1.NGAY_RA) AND (TO_NUMBER(SUBSTR(item.NGAY_YL, 1, 8)) < TO_NUMBER(SUBSTR(XML1.NGAY_VAO, 1, 8)) OR TO_NUMBER(SUBSTR(item.NGAY_YL, 1, 8)) > TO_NUMBER(SUBSTR(XML1.NGAY_RA, 1, 8)))) > 0",
    "CANH_BAO": "⛔ Phát hiện y lệnh thuốc nằm trước ngày vào viện hoặc sau ngày ra viện.",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_97",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_97",
    "TEN_QUY_TAC": "Thuốc nội trú sau ra viện",
    "DIEU_KIEN": "XML1.MA_LOAI_KCB == '3' && COUNT_IF(XML2, item => !IS_EMPTY(item.NGAY_YL) AND !IS_EMPTY(XML1.NGAY_RA) AND TO_NUMBER(SUBSTR(item.NGAY_YL, 1, 8)) > TO_NUMBER(SUBSTR(XML1.NGAY_RA, 1, 8))) > 0",
    "CANH_BAO": "⛔ [XUẤT TOÁN]: Phát sinh thuốc nội trú (XML2) sau ngày bệnh nhân đã làm thủ tục ra viện.",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ Đổi XML2.NGAY_YL trực tiếp sang COUNT_IF theo từng dòng thuốc để tránh lỗi collection access.",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_98",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_98",
    "TEN_QUY_TAC": "Thuốc sai tiền",
    "DIEU_KIEN": "COUNT_IF(XML2, item => TO_NUMBER(item.THANH_TIEN_BV) <> TO_NUMBER(item.SO_LUONG) * TO_NUMBER(item.DON_GIA)) > 0",
    "CANH_BAO": "⛔ Có thuốc tính tiền sai",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ Chuẩn hóa COUNT_IF sang lambda item => để so sánh thành tiền thuốc đúng trên từng dòng XML2.",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_99",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_99",
    "TEN_QUY_TAC": "Thuốc thiếu mã",
    "DIEU_KIEN": "COUNT_IF(XML2, item => IS_EMPTY(item.MA_THUOC)) > 0",
    "CANH_BAO": "⛔ Có thuốc không có mã hoạt chất",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ Bổ sung lambda item => để COUNT_IF đọc đúng MA_THUOC theo từng dòng XML2.",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_100",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_100",
    "TEN_QUY_TAC": "Thuốc thiếu Mã khoa",
    "DIEU_KIEN": "COUNT_IF(XML2, item => IS_EMPTY(item.MA_KHOA)) > 0",
    "CANH_BAO": "⛔ Dòng chi tiết thuốc bị thiếu Mã khoa chỉ định.",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_101",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_101",
    "TEN_QUY_TAC": "Thuốc thiếu ngày y lệnh",
    "DIEU_KIEN": "COUNT_IF(XML2, item => NOT IS_EMPTY(item.MA_THUOC) AND IS_EMPTY(item.NGAY_YL)) > 0",
    "CANH_BAO": "⚠️ Nguy hiểm: Thuốc thiếu ngày",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ Chuẩn hóa COUNT_IF sang lambda item => để tránh truy cập biến trần ngoài dòng XML2.",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_102",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_102",
    "TEN_QUY_TAC": "Thuốc tính tiền sai (SL x Giá)",
    "DIEU_KIEN": "COUNT_IF(XML2, item => !IS_EMPTY(item.THANH_TIEN_BV) AND ABS(TO_NUMBER(item.THANH_TIEN_BV) - (TO_NUMBER(item.SO_LUONG) * TO_NUMBER(item.DON_GIA))) > 1) > 0",
    "CANH_BAO": "⛔ Có dòng thuốc tại XML2 tính sai công thức (Số lượng x Đơn giá).",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ [Rà soát] Math.abs→ABS",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_103",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_103",
    "TEN_QUY_TAC": "Thứ tự Vào viện - Ra viện",
    "DIEU_KIEN": "TO_NUMBER(XML1.NGAY_RA) <= TO_NUMBER(XML1.NGAY_VAO)",
    "CANH_BAO": "⛔ [LỖI LOGIC]: Thời điểm ra viện không thể bằng hoặc trước thời điểm vào viện.",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_104",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_104",
    "TEN_QUY_TAC": "Tiền BN vượt Tổng chi BV",
    "DIEU_KIEN": "!IS_EMPTY(XML1.T_BNTT) AND !IS_EMPTY(XML1.T_TONGCHI_BV) AND TO_NUMBER(XML1.T_BNTT) > TO_NUMBER(XML1.T_TONGCHI_BV)",
    "CANH_BAO": "⛔ Tiền bệnh nhân tự trả lớn hơn tổng chi phí bệnh viện.",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_105",
    "TRANG_THAI": "OFF",
    "MA_LUAT": "XML_105",
    "TEN_QUY_TAC": "Tóm tắt HSBA rỗng (XML7)",
    "DIEU_KIEN": "1 == 0",
    "CANH_BAO": "⛔ [LIÊN THÔNG]: Bệnh nhân nội trú ra viện nhưng thiếu bảng tóm tắt hồ sơ bệnh án (XML7) để đẩy cổng.",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ [Production review] Vô hiệu hóa trước deploy: tham chiếu XML7 ngoài phạm vi payload XML1-XML6 đang dùng trong engine hiện tại. Điều kiện gốc: XML1.MA_LOAI_KCB == '3' && XML1.KET_QUA_DTRI NOT IN ('4','5') && COUNT(XML7) == 0",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_107",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_107",
    "TEN_QUY_TAC": "Tổng chi bệnh viện (T_TONGCHI_BV)",
    "DIEU_KIEN": "ABS(TO_NUMBER(XML1.T_TONGCHI_BV) - (TO_NUMBER(XML1.T_BHTT) + TO_NUMBER(XML1.T_BNCCT) + TO_NUMBER(XML1.T_BNTT) + TO_NUMBER(XML1.T_NGUONKHAC) + TO_NUMBER(XML1.T_NGOAIDS))) > 1",
    "CANH_BAO": "⛔ [KẾ TOÁN]: Tổng chi phí lệch so với tổng các nguồn thanh toán (BHYT + Cùng chi trả + Tự trả + Nguồn khác + Ngoài DS HIV/AIDS).",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ [Rà soát] Math.abs→ABS",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_108",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_108",
    "TEN_QUY_TAC": "Tổng chi khớp chi tiết",
    "DIEU_KIEN": "NOT IS_EMPTY(XML1.T_TONGCHI_BV) AND ABS(TO_NUMBER(XML1.T_TONGCHI_BV) - (SUM_IF(XML2, item => !IS_EMPTY(item.THANH_TIEN_BV), item => TO_NUMBER(item.THANH_TIEN_BV)) + SUM_IF(XML3, item => !IS_EMPTY(item.THANH_TIEN_BV), item => TO_NUMBER(item.THANH_TIEN_BV)))) > 2",
    "CANH_BAO": "⛔ Tổng chi BV không khớp chi tiết",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ Loại trường T_DVKT không còn phù hợp và đối chiếu trực tiếp T_TONGCHI_BV với tổng chi tiết XML2+XML3 bằng SUM_IF.",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_109",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_109",
    "TEN_QUY_TAC": "Tổng tiền BH > tổng tiền BV",
    "DIEU_KIEN": "(SUM_IF(XML2, item => !IS_EMPTY(item.THANH_TIEN_BH), item => TO_NUMBER(item.THANH_TIEN_BH)) + SUM_IF(XML3, item => !IS_EMPTY(item.THANH_TIEN_BH), item => TO_NUMBER(item.THANH_TIEN_BH))) > (SUM_IF(XML2, item => !IS_EMPTY(item.THANH_TIEN_BV), item => TO_NUMBER(item.THANH_TIEN_BV)) + SUM_IF(XML3, item => !IS_EMPTY(item.THANH_TIEN_BV), item => TO_NUMBER(item.THANH_TIEN_BV)))",
    "CANH_BAO": "🚨 BHYT thanh toán vượt tổng chi phí",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ Thay SUM không tồn tại trong engine bằng SUM_IF cho cả cột BHYT và BV ở XML2/XML3.",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_112",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_112",
    "TEN_QUY_TAC": "Trẻ em dưới 6 tuổi (TE)",
    "DIEU_KIEN": "STARTS_WITH(XML1.MA_THE_BHYT, 'TE') && TO_NUMBER(XML1.T_BNCCT) > 0",
    "CANH_BAO": "⛔ [PHÁP LÝ]: Thẻ trẻ em (TE) bắt buộc hưởng 100%, không được phát sinh tiền Cùng chi trả.",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ [Rà soát] .startsWith→STARTS_WITH()",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_114",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_114",
    "TEN_QUY_TAC": "Trống Cân nặng trẻ sơ sinh",
    "DIEU_KIEN": "DATEDIFF_DAY(SUBSTR(XML1.NGAY_SINH, 1, 8), SUBSTR(XML1.NGAY_VAO, 1, 8)) < 30 AND (XML1.CAN_NANG <= 0 OR IS_EMPTY(XML1.CAN_NANG))",
    "CANH_BAO": "⛔ [LÂM SÀNG]: Trẻ sơ sinh (<30 ngày) bắt buộc nhập cân nặng (gram) để kiểm soát liều lượng thuốc.",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ NGAY_SINH chỉ 8 ký tự (YYYYMMDD), cần SUBSTR(...,1,8) để bóc tách đúng trước khi tính DATEDIFF",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_115",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_115",
    "TEN_QUY_TAC": "Trống ngày trả kết quả",
    "DIEU_KIEN": "COUNT_IF(XML3, item => !IS_EMPTY(item.MA_DICH_VU) AND IS_EMPTY(item.NGAY_KQ) AND item.MA_NHOM NOT IN ('13', '14')) > 0",
    "CANH_BAO": "⛔ [DỮ LIỆU]: Dịch vụ kỹ thuật đã thực hiện nhưng bỏ trống thời điểm trả kết quả (NGAY_KQ) tại XML3.",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ Đổi XML3 từ truy cập trực tiếp sang COUNT_IF theo từng dòng và chuẩn hóa phủ định danh mục MA_NHOM bằng NOT IN.",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_116",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_116",
    "TEN_QUY_TAC": "Trùng dịch vụ trong cùng thời điểm",
    "DIEU_KIEN": "COUNT_IF(XML3, a => COUNT_IF(XML3, b => a.MA_DICH_VU == b.MA_DICH_VU && a.NGAY_YL == b.NGAY_YL) > 1) > 0",
    "CANH_BAO": "⚠️ Trùng dịch vụ cùng thời điểm",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ [Rà soát] MA_DV→MA_DICH_VU",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_119",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_119",
    "TEN_QUY_TAC": "Trùng lặp Công khám (Cùng ngày)",
    "DIEU_KIEN": "XML1.MA_LOAI_KCB == '1' && COUNT_IF(XML3, item => item.MA_NHOM == '13') > 1",
    "CANH_BAO": "⛔ [QUAN TRỌNG]: Một đợt khám ngoại trú không được tính quá 01 công khám chính (Trừ trường hợp khám chuyên khoa thêm).",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_120",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_120",
    "TEN_QUY_TAC": "Trùng lặp DVKT cùng ngày",
    "DIEU_KIEN": "COUNT_DISTINCT(XML3, item => item.MA_DICH_VU + SUBSTR(item.NGAY_YL, 1, 8)) < COUNT_IF(XML3, item => !IS_EMPTY(item.MA_DICH_VU))",
    "CANH_BAO": "⚠️ Có dấu hiệu chỉ định trùng 1 mã DVKT trong cùng một ngày.",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_121",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_121",
    "TEN_QUY_TAC": "Trùng lặp Thuốc cùng ngày (ngoại trú)",
    "DIEU_KIEN": "(MATCH_MA_LOAI_KCB(XML1.MA_LOAI_KCB, '1') OR MATCH_MA_LOAI_KCB(XML1.MA_LOAI_KCB, '4')) AND COUNT_DISTINCT(XML2, item => IS_EMPTY(item.MA_THUOC) || IS_EMPTY(SUBSTR(item.NGAY_YL, 1, 8)) ? '' : UPPER(item.MA_THUOC) + '|' + SUBSTR(item.NGAY_YL, 1, 8)) < COUNT_IF(XML2, item => !IS_EMPTY(item.MA_THUOC) && !IS_EMPTY(SUBSTR(item.NGAY_YL, 1, 8)))",
    "CANH_BAO": "⚠️ Có dấu hiệu kê trùng 1 loại thuốc nhiều lần trong cùng một ngày y lệnh (chỉ áp dụng ngoại trú / điều trị ban ngày; không áp dụng nội trú).",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ Khóa UPPER(MA_THUOC)+'|'+SUBSTR(NGAY_YL,1,8); bỏ qua dòng thiếu mã/ngày; MA_LOAI_KCB '1'|'4' — không nội trú 03/09.",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_122",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_122",
    "TEN_QUY_TAC": "Trùng lặp XN trong ngày",
    "DIEU_KIEN": "COUNT_IF(XML3, a => COUNT_IF(XML3, b => a.MA_DICH_VU == b.MA_DICH_VU && SUBSTR(a.NGAY_YL, 1, 8) == SUBSTR(b.NGAY_YL, 1, 8)) > 3) > 0 AND XML1.MA_LOAI_KCB == '1'",
    "CANH_BAO": "⚠️ [KIỂM SOÁT]: Thực hiện >3 lần cùng một loại xét nghiệm trong 1 ngày khám ngoại trú.",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ Thay CURRENT_DAY (không rõ ràng) bằng so sánh SUBSTR ngày y lệnh giữa các dòng XML3 cùng hồ sơ | ✏️ [Rà soát] MA_DV→MA_DICH_VU",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_124",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_124",
    "TEN_QUY_TAC": "XML thiếu hoàn toàn một cấu phần",
    "DIEU_KIEN": "IS_EMPTY(XML1) || IS_EMPTY(XML2) || IS_EMPTY(XML3)",
    "CANH_BAO": "🔴 Thiếu cấu phần XML",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_125",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_125",
    "TEN_QUY_TAC": "XML1 thiếu dữ liệu",
    "DIEU_KIEN": "IS_EMPTY(XML1)",
    "CANH_BAO": "⚠️ Thiếu dữ liệu XML1",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_128",
    "TRANG_THAI": "OFF",
    "MA_LUAT": "XML_128",
    "TEN_QUY_TAC": "XML2 có thứ tự dòng không liên tục",
    "DIEU_KIEN": "1 == 0",
    "CANH_BAO": "⚠️ STT XML2 không liên tục",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ [Production review] Vô hiệu hóa trước deploy: rule dùng INDEX(item) để suy vị trí dòng, không thuộc tập hàm hỗ trợ của engine hiện tại và QĐ 130 không cung cấp chỉ số vị trí dòng như một trường XML nghiệp vụ độc lập.",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_129",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_129",
    "TEN_QUY_TAC": "XML2 không có bản ghi",
    "DIEU_KIEN": "COUNT(XML2) = 0 AND TO_NUMBER(XML1.T_THUOC) > 0",
    "CANH_BAO": "⚠️ Thiếu dữ liệu XML2",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ Chỉ cảnh báo khi XML1 có phát sinh tiền thuốc. Tránh dương tính giả ở hồ sơ không có thuốc nên không cần XML2.",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_131",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_131",
    "TEN_QUY_TAC": "XML2 lệch MA_LK",
    "DIEU_KIEN": "COUNT_IF(XML2, item => item.MA_LK <> XML1.MA_LK) > 0",
    "CANH_BAO": "🔴 XML2 không khớp XML1",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_132",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_132",
    "TEN_QUY_TAC": "XML2 thiếu MA_LK",
    "DIEU_KIEN": "COUNT_IF(XML2, item => IS_EMPTY(item.MA_LK)) > 0",
    "CANH_BAO": "❗ XML2 thiếu mã liên kết",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_134",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_134",
    "TEN_QUY_TAC": "XML3 có dữ liệu nhưng XML2 bị rỗng",
    "DIEU_KIEN": "COUNT(XML3) > 0 AND COUNT(XML2) = 0 AND TO_NUMBER(XML1.T_THUOC) > 0",
    "CANH_BAO": "🔴 Có XML3 nhưng thiếu XML2",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ Chỉ cảnh báo khi XML1 thực sự có tiền thuốc. Không xem việc có XML3 là điều kiện đủ để kết luận XML2 phải tồn tại.",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_136",
    "TRANG_THAI": "OFF",
    "MA_LUAT": "XML_136",
    "TEN_QUY_TAC": "XML3 có thứ tự dòng không liên tục",
    "DIEU_KIEN": "1 == 0",
    "CANH_BAO": "⚠️ STT XML3 không liên tục",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ [Production review] Vô hiệu hóa trước deploy: rule dùng INDEX(item) để suy vị trí dòng, không thuộc tập hàm hỗ trợ của engine hiện tại và QĐ 130 không cung cấp chỉ số vị trí dòng như một trường XML nghiệp vụ độc lập.",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_137",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_137",
    "TEN_QUY_TAC": "XML3 có trường numeric nhưng chứa ký tự",
    "DIEU_KIEN": "COUNT_IF(XML3, item => !IS_NUMERIC(item.SO_LUONG) || (!IS_EMPTY(item.DON_GIA_BV) AND !IS_NUMERIC(item.DON_GIA_BV)) || (!IS_EMPTY(item.DON_GIA_BH) AND !IS_NUMERIC(item.DON_GIA_BH))) > 0",
    "CANH_BAO": "❗ Trường số chứa ký tự",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ Đổi DON_GIA không có trong XML3 chuẩn sang kiểm tra DON_GIA_BV/DON_GIA_BH khi có dữ liệu.",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_138",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_138",
    "TEN_QUY_TAC": "XML3 lệch MA_LK",
    "DIEU_KIEN": "COUNT_IF(XML3, item => item.MA_LK <> XML1.MA_LK) > 0",
    "CANH_BAO": "🔴 XML3 không khớp XML1",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_141",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_141",
    "TEN_QUY_TAC": "XML3 thiếu MA_LK",
    "DIEU_KIEN": "COUNT_IF(XML3, item => IS_EMPTY(item.MA_LK)) > 0",
    "CANH_BAO": "❗ XML3 thiếu mã liên kết",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_142",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_142",
    "TEN_QUY_TAC": "Y lệnh trước khi vào viện",
    "DIEU_KIEN": "COUNT_IF(XML2, item => LENGTH(item.NGAY_YL)=12 && item.NGAY_YL < XML1.NGAY_VAO ) > 0 OR COUNT_IF( XML3, item => LENGTH(item.NGAY_YL)=12 && item.NGAY_YL < XML1.NGAY_VAO ) > 0",
    "CANH_BAO": "⛔ [XUẤT TOÁN]: Y lệnh thuốc/dịch vụ phát sinh trước khi nhập viện.",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_143",
    "TRANG_THAI": "ON",
    "MA_LUAT": "XML_143",
    "TEN_QUY_TAC": "Thành tiền BHYT không cao hơn thành tiền BV (chi tiết)",
    "DIEU_KIEN": "COUNT_IF(XML2, item => !IS_EMPTY(item.THANH_TIEN_BH) && !IS_EMPTY(item.THANH_TIEN_BV) && TO_NUMBER(item.THANH_TIEN_BH) - TO_NUMBER(item.THANH_TIEN_BV) > 1) > 0 OR COUNT_IF(XML3, item => !IS_EMPTY(item.THANH_TIEN_BH) && !IS_EMPTY(item.THANH_TIEN_BV) && TO_NUMBER(item.THANH_TIEN_BH) - TO_NUMBER(item.THANH_TIEN_BV) > 1) > 0",
    "CANH_BAO": "⛔ [KẾ TOÁN]: Có dòng chi tiết mà thành tiền BHYT (THANH_TIEN_BH) cao hơn thành tiền bệnh viện (THANH_TIEN_BV) — không hợp lệ (chênh > 1đ).",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "✏️ Bổ sung so dòng XML2/XML3; bổ sung cho XML_109 (chỉ so tổng). Chỉ kiểm khi cả BH và BV đều có giá trị.",
    "NGUON_DU_LIEU": "DuLieu_LUAT_DU_LIEU (12).xlsx"
  },
  {
    "id": "SEED_DULIEU_CDSS_CM_01",
    "TRANG_THAI": "ON",
    "MA_LUAT": "CDSS_CM_01",
    "TEN_QUY_TAC": "CDSS Chuyên môn — Có mã ICD trên XML1 trùng kho phác đồ (chỉ kiểm tra tồn tại khóa ICD, không đối chiếu nội dung các cột phác đồ)",
    "DIEU_KIEN": "CO_KHO_TRI_THUC_PHAC_DO() AND CO_PHAC_DO_CDSS_CHO_BAT_CU_ICD_TREN_XML1(XML1)",
    "CANH_BAO": "ℹ️ [CHUYÊN MÔN — CDSS]: Ít nhất một mã ICD trên hồ sơ (chính/kèm, đã khử trùng) **có dòng tương ứng** trong bảng phác đồ đã nạp — **chỉ là nhắc tra cứu thủ công** (mục tiêu điều trị, dự phòng, theo dõi…). Engine **không** tự động so khớp nội dung phác đồ với thuốc/DVKT trên XML2/XML3 hay với Điều 15 Luật BHYT.",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "Phạm vi kỹ thuật: MAP chỉ lưu khóa ICD đã chuẩn hóa (bỏ dấu chấm), không đọc văn bản cột Điều trị/Mục tiêu. ICD lấy từ MA_BENH_CHINH, MA_BENH_KT, MA_BENHKEM (regex token). Ô MÃ ICD-10 dạng dải/ghi chú (vd. A15 - A16) không tách thành nhiều khóa — có thể không khớp mã đơn trên XML. Không kết luận sai phác đồ lâm sàng.",
    "NGUON_DU_LIEU": "CDSS Phác đồ BV + engine dong_co_giam_dinh",
    "MUC_DO": "Info"
  },
  {
    "id": "SEED_DULIEU_CDSS_CM_02",
    "TRANG_THAI": "OFF",
    "MA_LUAT": "CDSS_CM_02",
    "TEN_QUY_TAC": "CDSS Chuyên môn — Có kho phác đồ nhưng không có khóa ICD nào trên XML1 trùng bảng (sau gộp)",
    "DIEU_KIEN": "CO_KHO_TRI_THUC_PHAC_DO() AND KHONG_CO_PHAC_DO_CDSS_CHO_MA_ICD_GOP_TREN_XML1(XML1)",
    "CANH_BAO": "📋 [CHUYÊN MÔN — CDSS]: Đã nạp kho phác đồ nhưng **không mã ICD nào** trên XML1 (chính/kèm, đã khử trùng) trùng khóa trong bảng — gợi ý bổ sung dòng phác đồ hoặc kiểm tra ghi ICD. **Không** suy ra thiếu sót điều trị; có thể do lệch định dạng mã hoặc mã chỉ có trong văn bản ngoài XML1.",
    "DIEU_KIEN (Toán tử No-Code)": "",
    "GHI_CHU_SUA": "Mặc định OFF (dễ ồn khi kho lớn). Bật khi muốn nhắc đồng bộ dữ liệu Chuyên môn. Điều kiện chỉ so khớp ICD trên XML1 với MAP — không đánh giá lâm sàng.",
    "NGUON_DU_LIEU": "CDSS Phác đồ BV + engine dong_co_giam_dinh",
    "MUC_DO": "Warning"
  }
];
