/**
 * CODE CỨNG DỮ LIỆU BẢNG LUẬT: LUAT_CONG_KHAM
 * Nguồn: File Excel (59 quy tắc — CK_59 runtime built-in LAYER 4)
 * Đã lọc trùng: 0 dòng
 * ON/OFF: kiểm soát qua màn hình Quản lý Quy tắc ON/OFF
 * KHÔNG CẬP NHẬT THỦ CÔNG - dùng Import hoặc chạy lại script gen_hardcoded_rules.js
 */

const CACHE_RULES_HARDCODED = Object.freeze([
  { id: 'CK-001', MA_LUAT: 'CK_01', TEN_QUY_TAC: `Khám bệnh cho trẻ dưới 6 tuổi`, DIEU_KIEN: `(DATEDIFF_MONTH(SUBSTR(XML1.NGAY_SINH, 1, 8), SUBSTR(NOW, 1, 8)) < 72) AND COUNT_IF(XML3, item => item.MA_DV IN (DM_KHAM) AND item.MA_DV NOT IN (DM_KHAM_NHI)) > 0`, CANH_BAO: `⚠️ [CẢNH BÁO]: Bệnh nhi dưới 6 tuổi nhưng đang áp mã công khám người lớn. Kiểm tra lại danh mục khám Nhi khoa.`, TRANG_THAI: 'ON' },
  { id: 'CK-002', MA_LUAT: 'CK_02', TEN_QUY_TAC: `Khám bệnh ngày nghỉ/lễ`, DIEU_KIEN: `IS_HOLIDAY(SUBSTR(XML1.NGAY_VAO, 1, 8)) == TRUE AND COUNT_IF(XML3, item => item.MA_DV IN (DM_KHAM) AND item.MA_DV NOT IN (DM_KHAM_NGOAI_GIO)) > 0`, CANH_BAO: `⚠️ [CẢNH BÁO]: Ngày vào viện là ngày nghỉ/lễ nhưng đang áp mã công khám ngày thường. Vui lòng kiểm tra lại danh mục dịch vụ.`, TRANG_THAI: 'ON' },
  { id: 'CK-003', MA_LUAT: 'CK_03', TEN_QUY_TAC: `Định mức bàn khám theo giờ thực tế`, DIEU_KIEN: `COUNT_IF(XML3, item => item.MA_DV IN (DM_KHAM) AND !IS_EMPTY(item.MA_BAN_KHAM) AND SUBSTR(item.NGAY_YL, 1, 8) == SUBSTR(NOW, 1, 8)) > (65 / 8 * ((SUBSTR(XML1.NGAY_RA, 9, 2) * 60 + SUBSTR(XML1.NGAY_RA, 11, 2)) - (SUBSTR(XML1.NGAY_VAO, 9, 2) * 60 + SUBSTR(XML1.NGAY_VAO, 11, 2))) / 60)`, CANH_BAO: `⚠️ [CẢNH BÁO]: Số lượt khám vượt định mức cho phép tính theo thời gian làm việc thực tế (Ví dụ: 10 giờ làm việc tối đa là 81 lượt).`, TRANG_THAI: 'ON' },
  { id: 'CK-004', MA_LUAT: 'CK_04', TEN_QUY_TAC: `Công khám sau phẫu thuật trong ngày`, DIEU_KIEN: `COUNT_IF(XML3, item => item.MA_DV IN (DM_KHAM)) > 0 AND COUNT_IF(XML3, item => !IS_EMPTY(item.MA_PTTT) AND SUBSTR(item.NGAY_YL, 1, 8) == SUBSTR(XML1.NGAY_RA, 1, 8)) > 0 AND XML1.MA_LOAI_KCB != '1'`, CANH_BAO: `⚠️ [JCI Audit]: Bệnh nhân phẫu thuật và ra viện trong ngày. Kiểm tra xem công khám có bị tính trùng với phí hậu phẫu không.`, TRANG_THAI: 'ON' },
  { id: 'CK-005', MA_LUAT: 'CK_05', TEN_QUY_TAC: `Khám chuyên khoa tại khoa lâm sàng`, DIEU_KIEN: `XML1.MA_KHOA_VAO != (MA_KHOA_KHAM) AND COUNT_IF(XML3, item => item.MA_DV IN (DM_KHAM)) > 0 AND XML1.MA_LY_DO_VV != '2'`, CANH_BAO: `⚠️ [JCI Audit]: Khám chuyên khoa thực hiện tại khoa lâm sàng. Phải được tính như khám tại khoa khám bệnh (theo khoản 2 Điều 4b).`, TRANG_THAI: 'OFF' },
  { id: 'CK-006', MA_LUAT: 'CK_06', TEN_QUY_TAC: `Khám bệnh sau phẫu thuật (Hậu phẫu)`, DIEU_KIEN: `COUNT_IF(XML3, item => item.MA_DV IN (DM_KHAM)) > 0 AND COUNT_IF(XML3, item => !IS_EMPTY(item.MA_PTTT) AND DIFF_DAYS(SUBSTR(item.NGAY_YL, 1, 8), SUBSTR(XML1.NGAY_VAO, 1, 8)) >= 1 AND DIFF_DAYS(SUBSTR(item.NGAY_YL, 1, 8), SUBSTR(XML1.NGAY_VAO, 1, 8)) <= 10) > 0`, CANH_BAO: `⚠️ [JCI Audit]: Khám hậu phẫu trong vòng 10 ngày thường nằm trong gói phẫu thuật. Kiểm tra quy định thanh toán riêng.`, TRANG_THAI: 'ON' },
  { id: 'CK-007', MA_LUAT: 'CK_07', TEN_QUY_TAC: `Khám YHCT kết hợp Châm cứu/Xoa bóp`, DIEU_KIEN: `COUNT_IF(XML3, item => item.MA_DV IN (DM_KHAM_YHCT)) > 0 AND COUNT_IF(XML3, item => item.MA_DV IN (DM_VAT_LY_TRI_LIEU)) > 0`, CANH_BAO: `⚠️ [JCI Audit]: Kiểm tra tính hợp lý của công khám khi bệnh nhân thực hiện các dịch vụ phục hồi chức năng/YHCT kéo dài.`, TRANG_THAI: 'ON' },
  { id: 'CK-008', MA_LUAT: 'CK_08', TEN_QUY_TAC: `Ưu tiên khám người cao tuổi (> 80)`, DIEU_KIEN: `DATEDIFF_YEAR(SUBSTR(XML1.NGAY_SINH, 1, 8), SUBSTR(NOW, 1, 8)) > 80 AND COUNT_IF(XML3, item => item.MA_DV IN (DM_KHAM) AND DIFF_MINUTES(item.NGAY_YL, item.NGAY_KET_THUC) > 120) > 0`, CANH_BAO: `⚠️ [JCI Safety]: Người bệnh > 80 tuổi chờ khám quá 2 tiếng. Vi phạm quy trình ưu tiên và an toàn người bệnh.`, TRANG_THAI: 'ON' },
  { id: 'CK-009', MA_LUAT: 'CK_09', TEN_QUY_TAC: `Điều trị nội trú ban ngày (mã 04) và Công khám`, DIEU_KIEN: `XML1.MA_LOAI_KCB == '2' AND COUNT_IF(XML3, item => item.MA_DV IN (DM_KHAM)) > 1`, CANH_BAO: `⚠️ [KIỂM TRA]: Người bệnh thuộc loại hình điều trị nội trú ban ngày (mã 04 theo QĐ 824). Chỉ được tính 01 công khám khi bắt đầu đợt điều trị.`, TRANG_THAI: 'ON' },
  { id: 'CK-010', MA_LUAT: 'CK_10', TEN_QUY_TAC: `Công khám kết hợp YHCT và Hiện đại`, DIEU_KIEN: `COUNT_IF(XML3, item => item.MA_DV IN (DM_KHAM_YHCT)) > 0 AND COUNT_IF(XML3, item => item.MA_DV IN (DM_KHAM_HIEN_DAI)) > 0`, CANH_BAO: `⚠️ [KIỂM TRA]: Bệnh nhân khám kết hợp cả YHCT và Y học hiện đại. Kiểm tra tính hợp lệ của việc phối hợp phương pháp điều trị.`, TRANG_THAI: 'ON' },
  { id: 'CK-011', MA_LUAT: 'CK_11', TEN_QUY_TAC: `Khám và Chuyển viện trong ngày`, DIEU_KIEN: `XML1.MA_LOAI_RV == '2' AND COUNT_IF(XML3, item => item.MA_DV IN (DM_KHAM)) > 1`, CANH_BAO: `⚠️ [KIỂM TRA]: Bệnh nhân khám và chuyển viện ngay. Chỉ nên tính 01 công khám chính để đảm bảo hồ sơ chuyển tuyến sạch.`, TRANG_THAI: 'ON' },
  { id: 'CK-012', MA_LUAT: 'CK_12', TEN_QUY_TAC: `Khám bệnh và kê đơn thuốc đắt tiền`, DIEU_KIEN: `COUNT_IF(XML3, item => item.MA_DV IN (DM_KHAM)) > 0 AND COUNT_IF(XML2, item => TO_NUMBER(item.THANH_TIEN) > 10000000) > 0`, CANH_BAO: `⚠️ [KIỂM TRA]: Công khám đi kèm đơn thuốc giá trị cao. BHXH sẽ tập trung kiểm tra tính hợp lý của chỉ định lâm sàng.`, TRANG_THAI: 'ON' },
  { id: 'CK-013', MA_LUAT: 'CK_13', TEN_QUY_TAC: `Khám lại trong ngày (Không cấp cứu)`, DIEU_KIEN: `COUNT_REVISIT(XML1.MA_BN, SUBSTR(XML1.NGAY_VAO, 1, 8)) > 1 AND XML1.MA_LY_DO_VV != '2' AND COUNT_IF(XML3, item => item.MA_DV IN (DM_KHAM) AND TO_NUMBER(item.STT) >= 2 AND TO_NUMBER(item.THANH_TIEN) > (TO_NUMBER(item.DON_GIA) * 0.3)) > 0`, BIEU_THUC_CHUAN_HOA: `Runtime do special evaluator batchContext xử lý; biểu thức chuẩn tham chiếu: cùng bệnh nhân, cùng ngày, MA_LY_DO_VV/MA_LYDO_VVIEN khác mã 2 (cấp cứu QĐ 130), dòng công khám có STT >= 2 và THANH_TIEN > DON_GIA * 0.3.`, CANH_BAO: `⚠️ [KIỂM TRA]: Người bệnh khám lại ngay trong ngày (không phải cấp cứu). Lần khám này phải tính theo giá của lần khám thứ 02 trở đi (30%).`, TRANG_THAI: 'ON' },
  { id: 'CK-014', MA_LUAT: 'CK_14', TEN_QUY_TAC: `Chỉ định trùng (XML3: cùng MA_DV, cùng thời điểm)`, DIEU_KIEN: `COUNT_IF(XML3, item => !IS_EMPTY(item.MA_DV) && !IS_EMPTY(item.NGAY_YL) && COUNT_IF(XML3, other => item.MA_DV == other.MA_DV && SUBSTR(item.NGAY_YL, 1, 12) == SUBSTR(other.NGAY_YL, 1, 12)) >= 2) > 0`, CANH_BAO: `⚠️ [LÃNG PHÍ]: Trên XML3 có từ hai dòng trở lên cùng mã dịch vụ MA_DV và cùng mốc thời gian y lệnh (12 ký tự đầu NGAY_YL = yyyyMMddHHmm, coi như cùng phút). Coi là chỉ định trùng; cần biện minh lâm sàng/hội chẩn nếu hợp lệ. Chi tiết MA_DV + STT do engine ghép khi chạy kiểm tra.`, TRANG_THAI: 'ON' },
  { id: 'CK-015', MA_LUAT: 'CK_15', TEN_QUY_TAC: `Công khám kèm VTYT thay thế`, DIEU_KIEN: `COUNT_IF(XML3, item => item.MA_DV IN (DM_KHAM)) > 0 AND COUNT_IF(XML5, item => item.MA_VTYT IN (DM_VTYT_THAY_THE)) > 0`, CANH_BAO: `⚠️ [LOGIC LÂM SÀNG]: Khám bệnh có sử dụng vật tư thay thế (ví dụ: thủy tinh thể). Kiểm tra quy trình khám sàng lọc trước thủ thuật.`, TRANG_THAI: 'ON' },
  { id: 'CK-016', MA_LUAT: 'CK_16', TEN_QUY_TAC: `Khám chuyên khoa không khớp ICD-10`, DIEU_KIEN: `COUNT_IF(XML3, item => item.MA_DV IN (DM_KHAM_MAT)) > 0 AND XML1.MA_BENH NOT IN (ICD_MAT)`, CANH_BAO: `⚠️ [LOGIC LÂM SÀNG]: Khám chuyên khoa Mắt nhưng chẩn đoán chính không thuộc nhóm bệnh về Mắt.`, TRANG_THAI: 'ON' },
  { id: 'CK-017', MA_LUAT: 'CK_17', TEN_QUY_TAC: `Công khám và Thủ thuật trong ngày`, DIEU_KIEN: `COUNT_IF(XML3, item => item.MA_DV IN (DM_KHAM)) > 0 AND COUNT_IF(XML3, item => item.MA_DV IN (DM_THU_THUAT_LOAI_DAC_BIET)) > 0`, CANH_BAO: `⚠️ [LOGIC]: Bệnh nhân thực hiện thủ thuật loại đặc biệt trong ngày. Kiểm tra xem công khám đã được bao gồm trong phí thủ thuật chưa.`, TRANG_THAI: 'ON' },
  { id: 'CK-018', MA_LUAT: 'CK_18', TEN_QUY_TAC: `Khám bệnh và Vận chuyển cấp cứu`, DIEU_KIEN: `COUNT_IF(XML3, item => item.MA_DV IN (DM_KHAM)) > 0 AND COUNT_IF(XML3, item => item.MA_DV IN (DM_VAN_CHUYEN)) > 0`, CANH_BAO: `⚠️ [LOGIC]: Kiểm tra điều kiện thanh toán phí vận chuyển. Chỉ thanh toán khi có chỉ định chuyển viện cấp cứu hợp lệ.`, TRANG_THAI: 'ON' },
  { id: 'CK-019', MA_LUAT: 'CK_19', TEN_QUY_TAC: `Khám bệnh tiền phẫu`, DIEU_KIEN: `COUNT_IF(XML3, item => item.MA_DV IN (DM_KHAM)) > 0 AND COUNT_IF(XML3, item => !IS_EMPTY(item.MA_PTTT) AND SUBSTR(item.NGAY_YL, 1, 8) == SUBSTR(XML1.NGAY_VAO, 1, 8)) > 0`, CANH_BAO: `⚠️ [LƯU Ý]: Công khám tiền phẫu thường đã bao gồm trong quy trình phẫu thuật. Chỉ thanh toán nếu khám chuyên khoa khác biệt.`, TRANG_THAI: 'ON' },
  { id: 'CK-020', MA_LUAT: 'CK_20', TEN_QUY_TAC: `Khám theo yêu cầu (KTYC)`, DIEU_KIEN: `XML1.MA_LOAI_KCB == '1' AND COUNT_IF(XML3, item => item.MA_DV == (MA_KHAM_Y_CAU)) > 0`, CANH_BAO: `⚠️ [QUẢN TRỊ]: Công khám theo yêu cầu. Lưu ý tách phần chênh lệch giá dịch vụ để báo cáo riêng.`, TRANG_THAI: 'ON' },
  { id: 'CK-021', MA_LUAT: 'CK_21', TEN_QUY_TAC: `Công khám tại buồng lưu nhóm khám/điều trị ngoại trú`, DIEU_KIEN: `XML1.MA_LOAI_KCB == '1' AND DATEDIFF_DAY(SUBSTR(XML1.NGAY_VAO, 1, 8), SUBSTR(XML1.NGAY_RA, 1, 8)) > 0`, CANH_BAO: `⚠️ [QUẢN TRỊ]: Người bệnh thuộc nhóm khám bệnh/điều trị ngoại trú theo QĐ 824 nhưng có lưu theo dõi. Không được tính tiền giường nội trú cho trường hợp này.`, TRANG_THAI: 'ON' },
  { id: 'CK-022', MA_LUAT: 'CK_22', TEN_QUY_TAC: `Khoảng cách 2 lần khám < 15 phút`, DIEU_KIEN: `COUNT_IF(XML3, item => item.MA_DV IN (DM_KHAM) AND !IS_EMPTY(item.MA_BAC_SI) AND EXISTS(XML3, other => other != item AND other.MA_DV IN (DM_KHAM) AND other.MA_BAC_SI == item.MA_BAC_SI AND SUBSTR(other.NGAY_YL, 1, 8) == SUBSTR(item.NGAY_YL, 1, 8) AND DIFF_MINUTES(other.NGAY_YL, item.NGAY_YL) < 15)) > 0`, CANH_BAO: `⚠️ [RỦI RO TẦN SUẤT]: Hai lần khám của cùng 1 bác sĩ cho 2 bệnh nhân quá gần nhau. Rủi ro bị xuất toán vì không đảm bảo chất lượng.`, TRANG_THAI: 'ON' },
  // Nhóm dưới đây vẫn OFF do thiếu ngữ cảnh dữ liệu nền.
  // CK_23: cần tổng hợp chi phí công khám theo năm trên toàn bộ lượt khám của cùng bệnh nhân.
  // CK_25/CK_36/CK_38: cần map chuyên môn bác sĩ và chuyên khoa DVKT đã chuẩn hóa từ danh mục nhân sự/dịch vụ.
  // CK_26/CK_27: cần lịch sử tái khám liên hồ sơ (COUNT_VISIT, LAST_VISIT) ngoài phạm vi hồ sơ hiện tại.
  // CK_46: cần ngưỡng phân tuyến kỹ thuật (MAX_TUYEN_ALLOWED) theo cấu hình từng cơ sở.
  // CK_51/CK_52: cần đối chiếu theo bác sĩ trên nhiều hồ sơ/cơ sở trong cùng thời điểm.
  { id: 'CK-023', MA_LUAT: 'CK_23', TEN_QUY_TAC: `Công khám vượt định mức 2.000.000đ/năm`, DIEU_KIEN: `SUM_IF(XML3, item => item.MA_DV IN (DM_KHAM) AND SUBSTR(item.NGAY_YL, 1, 4) == SUBSTR(NOW, 1, 4), item => TO_NUMBER(item.THANH_TIEN)) > 2000000`, BIEU_THUC_CHUAN_HOA: `Runtime do special evaluator liên hồ sơ theo batchContext; biểu thức chuẩn là tổng THANH_TIEN nhóm công khám của cùng bệnh nhân trong cùng năm > 2.000.000.`, CANH_BAO: `⚠️ [RỦI RO]: Bệnh nhân có tổng tiền công khám trong năm quá cao. BHXH sẽ kiểm tra trục lợi thẻ BHYT.`, TRANG_THAI: 'OFF' },
  { id: 'CK-024', MA_LUAT: 'CK_24', TEN_QUY_TAC: `Chẩn đoán ICD-10 không đặc hiệu`, DIEU_KIEN: `XML1.MA_BENH IN ('R69') AND COUNT_IF(XML3, item => item.MA_DV IN (DM_KHAM)) > 0 AND XML1.MA_LY_DO_VV != '4'`, CANH_BAO: `⚠️ [SAI ICD]: Mã chẩn đoán chung chung (khám sức khỏe/không xác định). Rủi ro bị xuất toán vì không rõ tình trạng bệnh lý.`, TRANG_THAI: 'ON' },
  { id: 'CK-025', MA_LUAT: 'CK_25', TEN_QUY_TAC: `CCHN bác sĩ Nhi khoa khám người lớn`, DIEU_KIEN: `DATEDIFF_YEAR(SUBSTR(XML1.NGAY_SINH, 1, 8), SUBSTR(NOW, 1, 8)) > 16 AND COUNT_IF(XML3, item => item.MA_DV IN (DM_KHAM_NHI) AND item.MA_BAC_SI_CHUYEN_MON == 'NHI') > 0`, CANH_BAO: `⚠️ [SAI PHẠM VI]: Bác sĩ chuyên khoa Nhi thực hiện khám cho người bệnh trên 16 tuổi. Kiểm tra tính hợp pháp của CCHN.`, TRANG_THAI: 'OFF' },
  { id: 'CK-026', MA_LUAT: 'CK_26', TEN_QUY_TAC: `Khám bệnh mạn tính quá 12 lần/năm`, DIEU_KIEN: `COUNT_VISIT(XML1.MA_BN WHERE XML1.MA_BENH IN (DM_BENH_MAN_TINH) AND SUBSTR(XML1.NGAY_VAO, 1, 4) == SUBSTR(NOW, 1, 4)) > 12`, BIEU_THUC_CHUAN_HOA: `Runtime do special evaluator liên hồ sơ xử lý; biểu thức chuẩn là đếm số lượt cùng bệnh nhân, cùng năm, có MA_BENH thuộc DM_BENH_MAN_TINH > 12.`, CANH_BAO: `⚠️ [TẦN SUẤT]: Bệnh nhân mạn tính khám quá 12 lần/năm. Kiểm tra sự cần thiết của các lần khám phát sinh.`, TRANG_THAI: 'OFF' },
  { id: 'CK-027', MA_LUAT: 'CK_27', TEN_QUY_TAC: `Công khám bệnh án mạn tính`, DIEU_KIEN: `XML1.MA_BENH IN (DM_BENH_MAN_TINH) AND DATEDIFF_DAY(SUBSTR(LAST_VISIT.NGAY_VAO, 1, 8), SUBSTR(XML1.NGAY_VAO, 1, 8)) < 15`, BIEU_THUC_CHUAN_HOA: `Runtime do special evaluator liên hồ sơ xử lý; biểu thức chuẩn là hồ sơ bệnh mạn tính có lần tái khám gần nhất cách < 15 ngày.`, CANH_BAO: `⚠️ [TẦN SUẤT]: Bệnh nhân mạn tính tái khám dưới 15 ngày. Kiểm tra lý do khám sớm để tránh bị xuất toán tần suất.`, TRANG_THAI: 'OFF' },
  { id: 'CK-028', MA_LUAT: 'CK_28', TEN_QUY_TAC: `Khám và điều trị vật lý trị liệu`, DIEU_KIEN: `COUNT_IF(XML3, item => item.MA_DV IN (DM_KHAM)) > 0 AND COUNT_IF(XML3, item => item.MA_DV IN (DM_VLTL_KE_DAI)) > 0`, CANH_BAO: `⚠️ [TƯƠNG QUAN]: Kiểm tra sự cần thiết của công khám mỗi ngày khi bệnh nhân chỉ đến để tập VLTL theo liệu trình.`, TRANG_THAI: 'ON' },
  { id: 'CK-029', MA_LUAT: 'CK_29', TEN_QUY_TAC: `Công khám đi kèm thủ thuật thẩm mỹ`, DIEU_KIEN: `COUNT_IF(XML3, item => item.MA_DV IN (DM_KHAM)) > 0 AND COUNT_IF(XML3, item => item.MA_DV IN (DM_THAM_MY)) > 0`, CANH_BAO: `⛔ [ĐIỀU 23 LUẬT BHYT]: Khám bệnh để thực hiện dịch vụ thẩm mỹ không được BHYT chi trả.`, TRANG_THAI: 'ON' },
  { id: 'CK-030', MA_LUAT: 'CK_30', TEN_QUY_TAC: `Khám bệnh cho người nước ngoài`, DIEU_KIEN: `XML1.MA_QUOCTICH != '704' AND COUNT_IF(XML3, item => item.MA_DV IN (DM_KHAM_BHYT)) > 0 AND IS_EMPTY(XML1.MA_THE_BHYT)`, CANH_BAO: `⛔ [ĐỐI TƯỢNG]: Người nước ngoài không có thẻ BHYT. Không được áp mã công khám BHYT.`, TRANG_THAI: 'ON' },
  { id: 'CK-031', MA_LUAT: 'CK_31', TEN_QUY_TAC: `Khám sàng lọc trước tiêm chủng`, DIEU_KIEN: `COUNT_IF(XML3, item => item.MA_DV IN (DM_KHAM_SANG_LOC_TIEM)) > 0 AND COUNT_IF(XML3, item => item.MA_DV IN (DM_KHAM_BHYT)) > 0`, CANH_BAO: `⛔ [KHÔNG CHI TRẢ]: Khám sàng lọc trước tiêm chủng vắc xin không thuộc phạm vi thanh toán của quỹ BHYT.`, TRANG_THAI: 'ON' },
  { id: 'CK-032', MA_LUAT: 'CK_32', TEN_QUY_TAC: `Trùng lặp mã dịch vụ trong một hồ sơ`, DIEU_KIEN: `COUNT_IF(XML3, item => item.MA_DV IN (DM_KHAM)) > COUNT_DISTINCT(XML3, item => (item.MA_DV IN (DM_KHAM) ? item.MA_DV : ''))`, CANH_BAO: `⛔ [LỖI DỮ LIỆU]: Một mã công khám không được xuất hiện 02 lần trong cùng một hồ sơ (Nếu khám nhiều khoa phải dùng mã khoa khác nhau).`, TRANG_THAI: 'ON' },
  { id: 'CK-033', MA_LUAT: 'CK_33', TEN_QUY_TAC: `Công khám của BS chưa đăng ký`, DIEU_KIEN: `COUNT_IF(XML3, item => item.MA_DV IN (DM_KHAM) AND item.MA_BAC_SI NOT IN (DM_BS_DANG_KY_BHXH)) > 0`, CANH_BAO: `⛔ [PHÁP LÝ]: Bác sĩ thực hiện khám chưa được đăng ký hành nghề trên cổng kiểm tra BHYT.`, TRANG_THAI: 'ON' },
  { id: 'CK-034', MA_LUAT: 'CK_34', TEN_QUY_TAC: `Thiếu chữ ký số trên hồ sơ khám`, DIEU_KIEN: `COUNT_IF(XML3, item => item.MA_DV IN (DM_KHAM)) > 0 AND (IS_EMPTY(XML1.MA_BAC_SI_KY) OR IS_EMPTY(XML1.MA_TTDKY))`, CANH_BAO: `⛔ [PHÁP LÝ]: Hồ sơ công khám thiếu thông tin ký số (MA_BAC_SI_KY hoặc MA_TTDKY). Không đủ điều kiện đẩy lên cổng kiểm tra.`, TRANG_THAI: 'OFF' },
  { id: 'CK-035', MA_LUAT: 'CK_35', TEN_QUY_TAC: `Công khám của BS chưa có CCHN`, DIEU_KIEN: `COUNT_IF(XML3, item => item.MA_DV IN (DM_KHAM) AND item.MA_BAC_SI IN (DM_NHAN_VIEN_CHUA_CCHN)) > 0`, CANH_BAO: `⛔ [PHÁP LÝ]: Người thực hiện công khám chưa có Chứng chỉ hành nghề hợp lệ. BHXH từ chối thanh toán.`, TRANG_THAI: 'ON' },
  { id: 'CK-036', MA_LUAT: 'CK_36', TEN_QUY_TAC: `CCHN bác sĩ không phù hợp khoa`, DIEU_KIEN: `XML3.MA_BAC_SI.CHUYEN_MON NOT_MATCH XML3.MA_KHOA`, CANH_BAO: `⛔ [SAI CCHN]: Bác sĩ thực hiện công khám có chứng chỉ hành nghề không phù hợp với chuyên khoa của bàn khám.`, TRANG_THAI: 'OFF' },
  { id: 'CK-037', MA_LUAT: 'CK_37', TEN_QUY_TAC: `Khám bệnh cho đối tượng Quân đội`, DIEU_KIEN: `SUBSTR(XML1.MA_THE_BHYT, 1, 2) IN ('QN','CQ','CA','BV') AND COUNT_IF(XML3, item => item.MA_DV IN (DM_KHAM) AND item.MA_DV NOT IN (DM_KHAM_QUAN_Y)) > 0`, CANH_BAO: `⛔ [SAI DANH MỤC]: Đối tượng quân đội phải áp dụng danh mục và mức giá riêng theo quy định hiện hành.`, TRANG_THAI: 'ON' },
  { id: 'CK-038', MA_LUAT: 'CK_38', TEN_QUY_TAC: `Khám chuyên khoa tại khoa không tương ứng`, DIEU_KIEN: `COUNT_IF(XML3, item => item.MA_DV IN (DM_KHAM) AND item.MA_KHOA NOT_MATCH item.MA_CHUYEN_KHOA_DV) > 0`, CANH_BAO: `⛔ [SAI DANH MỤC]: Mã chuyên khoa của công khám không khớp với danh mục khoa phòng thực hiện.`, TRANG_THAI: 'OFF' },
  { id: 'CK-039', MA_LUAT: 'CK_39', TEN_QUY_TAC: `Khám Sức khỏe (Điều 23 Luật BHYT)`, DIEU_KIEN: `XML1.MA_LY_DO_VV == '4' AND COUNT_IF(XML3, item => item.MA_DV IN (DM_KHAM_BHYT)) > 0`, CANH_BAO: `⛔ [SAI ĐỐI TƯỢNG]: Khám sức khỏe không thuộc phạm vi chi trả của BHYT. Phải chuyển sang đối tượng Viện phí/Dịch vụ.`, TRANG_THAI: 'ON' },
  { id: 'CK-040', MA_LUAT: 'CK_40', TEN_QUY_TAC: `Cấp cứu không tính công khám lại`, DIEU_KIEN: `XML1.MA_LY_DO_VV == '2' AND COUNT_VISIT_IN_DAY(XML1.MA_BN, SUBSTR(XML1.NGAY_VAO, 1, 8)) > 1 AND COUNT_IF(XML3, item => item.MA_DV IN (DM_KHAM) AND TO_NUMBER(item.THANH_TIEN) < TO_NUMBER(item.DON_GIA)) > 0`, BIEU_THUC_CHUAN_HOA: `Runtime do special evaluator batchContext xử lý; biểu thức chuẩn là hồ sơ cấp cứu (mã lý do vào viện 2 — QĐ 130) trong ngày có dòng công khám bị tính thấp hơn DON_GIA thay vì 100%.`, CANH_BAO: `⛔ [SAI ĐƠN GIÁ]: Trường hợp cấp cứu được tính là một lần khám mới (100% giá), không tính theo tỷ lệ 30% như khám lại thông thường.`, TRANG_THAI: 'ON' },
  { id: 'CK-041', MA_LUAT: 'CK_41', TEN_QUY_TAC: `Tỷ lệ thanh toán lần khám thứ 2+`, DIEU_KIEN: `COUNT_IF(XML3, item => item.MA_DV IN (DM_KHAM)) >= 2 AND COUNT_IF(XML3, item => item.MA_DV IN (DM_KHAM) AND TO_NUMBER(item.STT) >= 2 AND TO_NUMBER(item.THANH_TIEN) > (TO_NUMBER(item.DON_GIA) * 0.3)) > 0`, CANH_BAO: `⛔ [SAI ĐƠN GIÁ]: Từ lần khám thứ 02 trở đi chỉ được tính 30% mức giá của 01 lần khám bệnh. Vui lòng kiểm tra lại trường XML3.THANH_TIEN.`, TRANG_THAI: 'ON' },
  { id: 'CK-042', MA_LUAT: 'CK_42', TEN_QUY_TAC: `Công khám buồng lưu nhóm khám/điều trị ngoại trú quá 24h`, DIEU_KIEN: `XML1.MA_LOAI_KCB == '1' AND DIFF_MINUTES(XML1.NGAY_VAO, XML1.NGAY_RA) > 1440`, CANH_BAO: `⛔ [SAI LOẠI HÌNH]: Nhóm khám bệnh/điều trị ngoại trú theo QĐ 824 lưu theo dõi quá 24h (1440 phút). Phải chuyển sang điều trị nội trú (mã 03/09) hoặc điều trị nội trú ban ngày (mã 04).`, TRANG_THAI: 'ON' },
  { id: 'CK-043', MA_LUAT: 'CK_43', TEN_QUY_TAC: `Khám Nam khoa cho Nữ giới`, DIEU_KIEN: `COUNT_IF(XML3, item => item.MA_DV IN (DM_KHAM_NAM_KHOA)) > 0 AND XML1.GIOI_TINH == '2'`, CANH_BAO: `⛔ [SAI LOGIC]: Công khám chuyên khoa Nam khoa không phù hợp với giới tính người bệnh.`, TRANG_THAI: 'ON' },
  { id: 'CK-044', MA_LUAT: 'CK_44', TEN_QUY_TAC: `Khám Sản/Phụ khoa cho Nam giới`, DIEU_KIEN: `COUNT_IF(XML3, item => item.MA_DV IN (DM_KHAM_SAN_PHU)) > 0 AND XML1.GIOI_TINH == '1'`, CANH_BAO: `⛔ [SAI LOGIC]: Công khám chuyên khoa Sản/Phụ khoa không phù hợp với giới tính người bệnh.`, TRANG_THAI: 'ON' },
  { id: 'CK-045', MA_LUAT: 'CK_45', TEN_QUY_TAC: `Khám bệnh tại trạm vệ tinh`, DIEU_KIEN: `XML1.MA_CSKCB != (MA_CHINH) AND COUNT_IF(XML3, item => item.MA_DV == (MA_KHAM_HANG_1)) > 0`, CANH_BAO: `⛔ [SAI MỨC GIÁ]: Khám tại phòng khám vệ tinh/trạm y tế phải áp mức giá theo hạng của cơ sở đó (thường là hạng 3, 4).`, TRANG_THAI: 'ON' },
  { id: 'CK-046', MA_LUAT: 'CK_46', TEN_QUY_TAC: `Khám bệnh vượt tuyến kỹ thuật`, DIEU_KIEN: `XML1.MA_TUYEN_KCB > {MAX_TUYEN_ALLOWED}`, CANH_BAO: `⛔ [SAI TUYẾN]: Cơ sở thực hiện công khám vượt quá phân tuyến kỹ thuật được phép.`, TRANG_THAI: 'OFF' },
  { id: 'CK-047', MA_LUAT: 'CK_47', TEN_QUY_TAC: `Công khám của BS đang nghỉ phép`, DIEU_KIEN: `COUNT_IF(XML3, item => item.MA_DV IN (DM_KHAM) AND item.MA_BAC_SI IN (DM_BS_NGHI_PHEP)) > 0 AND SUBSTR(XML1.NGAY_VAO, 1, 8) == SUBSTR(NOW, 1, 8)`, CANH_BAO: `⛔ [TRỤC LỢI]: Bác sĩ đang trong danh sách nghỉ phép/hội thảo nhưng vẫn phát sinh công khám trên hệ thống.`, TRANG_THAI: 'ON' },
  { id: 'CK-048', MA_LUAT: 'CK_48', TEN_QUY_TAC: `Khám chuyên khoa và Bác sĩ Gia đình`, DIEU_KIEN: `COUNT_IF(XML3, item => item.MA_DV IN (DM_KHAM_CK)) > 0 AND COUNT_IF(XML3, item => item.MA_DV IN (DM_KHAM_BSGD)) > 0`, CANH_BAO: `⛔ [TRÙNG LẶP]: Đã tính công khám bác sĩ gia đình thì không tính công khám chuyên khoa trong cùng một lần khám (trừ trường hợp chuyển tuyến).`, TRANG_THAI: 'ON' },
  { id: 'CK-049', MA_LUAT: 'CK_49', TEN_QUY_TAC: `Khám bệnh cho người bệnh có thẻ khóa`, DIEU_KIEN: `XML1.MA_THE_BHYT IN (DM_THE_KHOA_BHXH)`, CANH_BAO: `⛔ [TỪ CHỐI]: Thẻ BHYT đã bị cơ quan bảo hiểm khóa hoặc thu hồi trên hệ thống quốc gia.`, TRANG_THAI: 'ON' },
  { id: 'CK-050', MA_LUAT: 'CK_50', TEN_QUY_TAC: `Khám bệnh khi thẻ BHYT hết hạn`, DIEU_KIEN: `!IS_EMPTY(XML1.NGAY_VAO) AND IS_EMPTY(XML1.GT_THE_TU)

AND !IS_EMPTY(XML1.GT_THE_DEN) AND (

  SUBSTR(XML1.NGAY_VAO,1,8) < XML1.GT_THE_TU

  OR SUBSTR(XML1.NGAY_VAO,1,8) > XML1.GT_THE_DEN)`, CANH_BAO: `⛔ [TỪ CHỐI]: Thẻ BHYT đã hết giá trị sử dụng tại thời điểm công khám được thực hiện.`, TRANG_THAI: 'ON' },
  { id: 'CK-051', MA_LUAT: 'CK_51', TEN_QUY_TAC: `Bác sĩ khám vượt quá 02 cơ sở/ngày`, DIEU_KIEN: `COUNT_DISTINCT(XML1.MA_CSKCB WHERE XML3.MA_BAC_SI == {ID} AND SUBSTR(XML1.NGAY_VAO, 1, 8) == SUBSTR(NOW, 1, 8)) > 2`, BIEU_THUC_CHUAN_HOA: `Runtime do special evaluator liên hồ sơ xử lý; biểu thức chuẩn là số cơ sở KCB khác nhau của cùng MA_BAC_SI trong cùng ngày > 2.`, CANH_BAO: `⛔ [VI PHẠM CCHN]: Một bác sĩ không được đăng ký hành nghề và tính công khám tại quá 02 cơ sở y tế trong cùng một ngày.`, TRANG_THAI: 'OFF' },
  { id: 'CK-052', MA_LUAT: 'CK_52', TEN_QUY_TAC: `Trùng lặp công khám cùng giờ`, DIEU_KIEN: `COUNT_IF(XML3, item => item.MA_DV IN (DM_KHAM) AND !IS_EMPTY(item.MA_BAC_SI) AND !IS_EMPTY(item.NGAY_YL) AND EXISTS(XML3, other => other != item AND other.MA_DV IN (DM_KHAM) AND other.MA_BAC_SI == item.MA_BAC_SI AND SUBSTR(other.NGAY_YL, 1, 12) == SUBSTR(item.NGAY_YL, 1, 12))) > 0`, BIEU_THUC_CHUAN_HOA: `Runtime do special evaluator theo bác sĩ và mốc thời gian chuẩn hóa; biểu thức chuẩn là cùng MA_BAC_SI phát sinh > 1 lượt khám trùng timestamp mức phút.`, CANH_BAO: `⛔ [VÔ LÝ]: Một bác sĩ không thể thực hiện khám cho 2 bệnh nhân tại cùng một thời điểm (phút/giây).`, TRANG_THAI: 'OFF' },
  { id: 'CK-053', MA_LUAT: 'CK_53', TEN_QUY_TAC: `Trần thanh toán 200% công khám`, DIEU_KIEN: `COUNT_IF(XML3, item => item.MA_DV IN (DM_KHAM)) > 0 AND ALL(XML3, item => !(item.MA_DV IN (DM_KHAM)) OR SUM_IF(XML3, row => row.MA_DV IN (DM_KHAM), row => TO_NUMBER(row.THANH_TIEN)) > (TO_NUMBER(item.DON_GIA) * 2))`, CANH_BAO: `⛔ [VƯỢT ĐỊNH MỨC]: Mức thanh toán tối đa chi phí khám bệnh trong một lần đến khám không được quá 02 lần mức giá của 01 lần khám bệnh cao nhất.`, TRANG_THAI: 'ON' },
  { id: 'CK-054', MA_LUAT: 'CK_54', TEN_QUY_TAC: `Vượt định mức 65 lượt/bàn/8h`, DIEU_KIEN: `COUNT_IF(XML3, item => item.MA_DV IN (DM_KHAM) AND !IS_EMPTY(item.MA_BAN_KHAM)) > 65 AND COUNT_IF(XML3, item => item.MA_DV IN (DM_KHAM) AND TO_NUMBER(item.STT) >= 66 AND TO_NUMBER(item.THANH_TIEN) > (TO_NUMBER(item.DON_GIA) * 0.5)) > 0`, CANH_BAO: `⛔ [VƯỢT TỶ TRỌNG]: Bàn khám vượt 65 lượt/08 giờ. Từ lượt thứ 66 trở đi cơ quan BHXH chỉ thanh toán 50% mức giá khám bệnh.`, TRANG_THAI: 'ON' },
  { id: 'CK-055', MA_LUAT: 'CK_55', TEN_QUY_TAC: `Điều trị nội trú (mã 03/09) không qua khoa khám`, DIEU_KIEN: `XML1.MA_LOAI_KCB == '3' AND COUNT_IF(XML3, item => item.MA_DV IN (DM_KHAM)) > 0 AND XML1.MA_KHOA_VAO != (MA_KHOA_KHAM) AND XML1.MA_LY_DO_VV != '2'`, CANH_BAO: `⛔ [XUẤT TOÁN]: Người bệnh vào điều trị nội trú theo QĐ 824 (mã 03 hoặc 09) trực tiếp tại khoa lâm sàng, không đăng ký khám tại khoa khám bệnh thì không được thanh toán tiền khám.`, TRANG_THAI: 'OFF' },
  { id: 'CK-056', MA_LUAT: 'CK_56', TEN_QUY_TAC: `Khám bệnh kèm Hội chẩn`, DIEU_KIEN: `COUNT_IF(XML3, item => item.MA_DV IN (DM_KHAM)) > 0 AND COUNT_IF(XML3, item => item.MA_DV IN (DM_HOI_CHAN)) > 0`, CANH_BAO: `⛔ [XUẤT TOÁN]: Đã tính công khám thì không tính tiền hội chẩn chuyên khoa cho cùng một bác sĩ thực hiện.`, TRANG_THAI: 'ON' },
  { id: 'CK-057', MA_LUAT: 'CK_57', TEN_QUY_TAC: `Khám bệnh trong ngày ra viện nội trú`, DIEU_KIEN: `XML1.MA_LOAI_KCB == '3' AND COUNT_IF(XML3, item => item.MA_DV IN (DM_KHAM) AND SUBSTR(item.NGAY_YL, 1, 8) == SUBSTR(XML1.NGAY_RA, 1, 8)) > 0`, CANH_BAO: `⛔ [XUẤT TOÁN]: Không tính công khám nhóm khám bệnh/điều trị ngoại trú trong ngày người bệnh làm thủ tục ra viện từ đợt điều trị nội trú (mã 03/09) tại cùng một cơ sở.`, TRANG_THAI: 'ON' },
  { id: 'CK-058', MA_LUAT: 'CK_58', TEN_QUY_TAC: `Khám nhiều chuyên khoa cùng Khoa`, DIEU_KIEN: `COUNT_DISTINCT(XML3, item => (item.MA_DV IN (DM_KHAM) AND !IS_EMPTY(item.MA_KHOA) AND item.MA_KHOA != 'KHOA_KHAM_BENH') ? (item.MA_KHOA + '|' + item.MA_DV) : '') > COUNT_DISTINCT(XML3, item => (item.MA_DV IN (DM_KHAM) AND !IS_EMPTY(item.MA_KHOA) AND item.MA_KHOA != 'KHOA_KHAM_BENH') ? item.MA_KHOA : '')`, CANH_BAO: `⛔ [XUẤT TOÁN]: Trong cùng một khoa lâm sàng chỉ được tính 01 lần khám bệnh (trừ khoa Khám bệnh đa khoa).`, TRANG_THAI: 'ON' },
  { id: 'CK-059', MA_LUAT: 'CK_59', TEN_QUY_TAC: `BS một CCHN — nhiều loại công khám / chuyên khoa`, DIEU_KIEN: `BUILT-IN: giamDinhBsMotCchnNhieuChuyenKhoaCongKham (dong_co LAYER 4)`, CANH_BAO: `⛔ [XUẤT TOÁN] [CK_59]: Một bác sỹ với một CCHN thực hiện nhiều loại công khám (chuyên khoa) trong cùng lượt khám — rủi ro xuất toán phạm vi hành nghề.`, TRANG_THAI: 'ON' },
]);

export const layDanhSachLuatCongKhamHardcoded = () => CACHE_RULES_HARDCODED.map((row) => ({ ...row }));
