/**
 * CODE CỨNG DỮ LIỆU BẢNG LUẬT: LUAT_HOP_DONG
 * Nguồn: File Excel (23 quy tắc)
 * Đã lọc trùng: 0 dòng
 * ON/OFF: kiểm soát qua màn hình Quản lý Quy tắc ON/OFF
 * KHÔNG CẬP NHẬT THỦ CÔNG - dùng Import hoặc chạy lại script gen_hardcoded_rules.js
 */

const CACHE_RULES_HARDCODED = Object.freeze([
  { id: 'HD-001', MA_LUAT: 'HD_01', TEN_QUY_TAC: `Giờ tiếp đón ngoại trú sai quy định`, DIEU_KIEN: `XML1.MA_LOAI_KCB == '01' AND NOT ((SUBSTR(XML1.NGAY_VAO, 9, 4) BETWEEN '0700' AND '1130') OR (SUBSTR(XML1.NGAY_VAO, 9, 4) BETWEEN '1300' AND '1630'))`, CANH_BAO: `⛔ VI PHẠM ĐIỀU 1 (2.2.1): Tiếp đón ngoại trú ngoài giờ hành chính thỏa thuận (07:00-11:30 và 13:00-16:30).`, TRANG_THAI: 'ON' },
  { id: 'HD-002', MA_LUAT: 'HD_02', TEN_QUY_TAC: `KCB ngoại trú vào ngày Lễ/Tết`, DIEU_KIEN: `XML1.MA_LOAI_KCB == '01'
AND IS_HOLIDAY(SUBSTR(XML1.NGAY_VAO,1,8))`, CANH_BAO: `⛔ VI PHẠM ĐIỀU 1 (2.2.1.d): Hợp đồng quy định KHÔNG tổ chức KCB ngoại trú vào ngày Lễ, Tết.`, TRANG_THAI: 'ON' },
  { id: 'HD-003', MA_LUAT: 'HD_03', TEN_QUY_TAC: `Khám bệnh ngày Chủ nhật`, DIEU_KIEN: `XML1.MA_LOAI_KCB == '01' AND DAY_OF_WEEK(SUBSTR(XML1.NGAY_VAO, 1, 8)) == 1 AND NOT ((SUBSTR(XML1.NGAY_VAO, 9, 4) BETWEEN '0700' AND '1130') OR (SUBSTR(XML1.NGAY_VAO, 9, 4) BETWEEN '1300' AND '1630'))`, CANH_BAO: `⚠️ CẢNH BÁO: Giờ khám Chủ nhật phải đúng khung giờ hành chính theo thỏa thuận tại mục 2.2.1.c.`, TRANG_THAI: 'OFF' },
  { id: 'HD-004', MA_LUAT: 'HD_04', TEN_QUY_TAC: `Dữ liệu ngoài thời hạn Hợp đồng`, DIEU_KIEN: `TO_NUMBER(SUBSTR(XML1.NGAY_VAO, 1, 8)) < 20260101 OR TO_NUMBER(SUBSTR(XML1.NGAY_VAO, 1, 8)) > 20261231`, CANH_BAO: `⛔ VI PHẠM ĐIỀU 5: Thời điểm KCB nằm ngoài thời hạn hiệu lực hợp đồng (01/01/2026 - 31/12/2026).`, TRANG_THAI: 'ON' },
  { id: 'HD-005', MA_LUAT: 'HD_05', TEN_QUY_TAC: `Vượt số bàn khám phê duyệt`, DIEU_KIEN: `XML1.MA_LOAI_KCB == '01' AND COUNT_DISTINCT(XML3, MA_NHOM == '1') > 19`, CANH_BAO: `⚠️ CẢNH BÁO: Số lượng bàn khám hoạt động vượt quá 19 bàn đã phê duyệt tại Điều 1 (2.3.a).`, TRANG_THAI: 'ON' },
  { id: 'HD-006', MA_LUAT: 'HD_06', TEN_QUY_TAC: `Sai mã cơ sở KCB`, DIEU_KIEN: `XML1.MA_CSKCB != '94170'`, CANH_BAO: `⛔ SAI LỆCH: Mã cơ sở KCB trên hồ sơ không khớp với mã 94170 (BV Quốc tế Phương Châu Sóc Trăng).`, TRANG_THAI: 'ON' },
  { id: 'HD-007', MA_LUAT: 'HD_07', TEN_QUY_TAC: `Gửi dữ liệu chậm (sau khi ra viện)`, DIEU_KIEN: `DATEDIFF_HOUR(XML1.NGAY_RA, CURRENT_TIMESTAMP) > 24`, CANH_BAO: `⚠️ VI PHẠM ĐIỀU 4 (2.h): Trách nhiệm gửi dữ liệu điện tử ngay sau khi kết thúc lượt KCB từ ngày 01/01/2026.`, TRANG_THAI: 'OFF' },
  { id: 'HD-008', MA_LUAT: 'HD_08', TEN_QUY_TAC: `Khám sức khỏe/Theo yêu cầu (Điều 23 Luật BHYT)`, DIEU_KIEN: `XML1.MA_LYDO_VVIEN == '4'`, BIEU_THUC_CHUAN_HOA: `Ưu tiên alias nghiệp vụ XML1.MA_LY_DO_VV == '4'; runtime giữ nguyên MA_LYDO_VVIEN để không đổi hành vi dữ liệu cũ.`, CANH_BAO: `⛔ Vi phạm Điều 23 Luật BHYT: Hồ sơ thuộc diện khám sức khỏe hoặc theo yêu cầu, không thuộc phạm vi chi trả của Quỹ BHYT theo Hợp đồng.`, TRANG_THAI: 'ON' },
  { id: 'HD-009', MA_LUAT: 'HD_09', TEN_QUY_TAC: `Sai mã phương thức thanh toán`, DIEU_KIEN: `XML1.MA_PTTT != '1'`, CANH_BAO: `⚠️ Cảnh báo: Phương thức thanh toán không đúng với thỏa thuận trong Hợp đồng (Thanh toán theo giá dịch vụ).`, TRANG_THAI: 'ON' },
  { id: 'HD-010', MA_LUAT: 'HD_10', TEN_QUY_TAC: `Thiếu căn cứ thanh toán xét nghiệm (JCI Audit)`, DIEU_KIEN: `COUNT_IF(XML4, IS_EMPTY(item.CHI_SO_XN_BT)) > 0`, CANH_BAO: `⚠️ JCI Audit: Kết quả cận lâm sàng thiếu dải chỉ số bình thường, vi phạm tiêu chuẩn chất lượng cam kết trong Hợp đồng.`, TRANG_THAI: 'ON' },
  { id: 'HD-011', MA_LUAT: 'HD_11', TEN_QUY_TAC: `Dịch vụ ngoài danh mục phê duyệt`, DIEU_KIEN: `XML3.MA_DICH_VU == ""`, CANH_BAO: `⛔ Vi phạm Điều 1: Dịch vụ kỹ thuật thực hiện không có mã hoặc chưa được phê duyệt trong Phụ lục Hợp đồng.`, TRANG_THAI: 'OFF' },
  { id: 'HD-012', MA_LUAT: 'HD_12', TEN_QUY_TAC: `Hồ sơ sai mã hóa địa bàn hành chính`, DIEU_KIEN: `!IS_EMPTY(XML1.MAXA_CU_TRU) AND LEN(XML1.MAXA_CU_TRU) != 5`, CANH_BAO: `⛔ Lỗi cấu trúc dữ liệu: Mã xã/phường thường trú phải đúng 5 chữ số theo danh mục TCTK để xác định khu vực hưởng lợi.`, TRANG_THAI: 'ON' },
  { id: 'HD-013', MA_LUAT: 'HD_13', TEN_QUY_TAC: `Thuốc không thuộc danh mục Hợp đồng`, DIEU_KIEN: `COUNT_IF(XML2, !IS_EMPTY(item.TEN_THUOC) AND IS_EMPTY(item.MA_THUOC)) > 0`, CANH_BAO: `⛔ Vi phạm Điều 3: Phát hiện thuốc không có mã trong danh mục thuốc được Quỹ BHYT chi trả.`, TRANG_THAI: 'ON' },
  { id: 'HD-014', MA_LUAT: 'HD_14', TEN_QUY_TAC: `Y lệnh ngoài thời gian điều trị`, DIEU_KIEN: `COUNT_IF(XML3, item => !IS_EMPTY(item.NGAY_YL) AND !IS_EMPTY(XML1.NGAY_VAO) AND !IS_EMPTY(XML1.NGAY_RA) AND (TO_NUMBER(item.NGAY_YL) < TO_NUMBER(XML1.NGAY_VAO) OR TO_NUMBER(item.NGAY_YL) > TO_NUMBER(XML1.NGAY_RA))) > 0`, CANH_BAO: `⛔ Y lệnh ngoài thời gian điều trị: Thời điểm ra y lệnh nằm ngoài khoảng NGAY_VAO - NGAY_RA của lượt KCB.`, TRANG_THAI: 'ON' },
  { id: 'HD-015', MA_LUAT: 'HD_15', TEN_QUY_TAC: `KQ trước y lệnh (chỉ CLS thực sự)`, DIEU_KIEN: `COUNT_IF(XML3, item => (item.MA_NHOM == '3' OR item.MA_NHOM == '4') AND !IS_EMPTY(item.NGAY_KQ) AND !IS_EMPTY(item.NGAY_YL) AND TO_NUMBER(item.NGAY_KQ) < TO_NUMBER(item.NGAY_YL)) > 0`, CANH_BAO: `⛔ KQ trước y lệnh (chỉ CLS thực sự): Ngày trả kết quả CLS sớm hơn ngày ra y lệnh.`, TRANG_THAI: 'ON' },
  { id: 'HD-016', MA_LUAT: 'HD_16', TEN_QUY_TAC: `Thiếu bác sĩ chỉ định (chỉ CLS có yêu cầu ký)`, DIEU_KIEN: `COUNT_IF(XML3, item => (item.MA_NHOM == '3' OR item.MA_NHOM == '4') AND !IS_EMPTY(item.MA_DICH_VU) AND IS_EMPTY(item.MA_BAC_SI)) > 0`, CANH_BAO: `🟠 Thiếu bác sĩ chỉ định: Dịch vụ CLS có mã nhưng thiếu thông tin bác sĩ chỉ định (MA_BAC_SI).`, TRANG_THAI: 'ON' },
  { id: 'HD-017', MA_LUAT: 'HD_17', TEN_QUY_TAC: `Số lượng không hợp lệ`, DIEU_KIEN: `COUNT_IF(XML3, item => !IS_EMPTY(item.SO_LUONG) AND TO_NUMBER(item.SO_LUONG) <= 0) > 0`, CANH_BAO: `🔴 Số lượng ≤ 0 (không hợp lệ): Dịch vụ/thuốc có số lượng không hợp lệ trong XML3.`, TRANG_THAI: 'ON' },
  { id: 'HD-018', MA_LUAT: 'HD_18', TEN_QUY_TAC: `Sai cấu trúc thanh toán`, DIEU_KIEN: `COUNT_IF(XML3, item => !IS_EMPTY(item.DON_GIA) AND !IS_EMPTY(item.THANH_TIEN) AND TO_NUMBER(item.DON_GIA) == 0 AND TO_NUMBER(item.THANH_TIEN) > 0) > 0`, BIEU_THUC_CHUAN_HOA: `Khi chuẩn hóa dữ liệu giá, ưu tiên DON_GIA_BH/DON_GIA_BV rồi mới fallback DON_GIA; runtime hiện vẫn giữ nguyên DIEU_KIEN để không đổi kết quả.`, CANH_BAO: `🔴 Thanh toán sai cấu trúc: Đơn giá = 0 nhưng thành tiền > 0, sai logic tính tiền.`, TRANG_THAI: 'ON' },
  { id: 'HD-019', MA_LUAT: 'HD_19', TEN_QUY_TAC: `Sai công thức tiền (có tolerance)`, DIEU_KIEN: `COUNT_IF(XML3, item => !IS_EMPTY(item.SO_LUONG) AND !IS_EMPTY(item.DON_GIA) AND !IS_EMPTY(item.THANH_TIEN) AND ABS(TO_NUMBER(item.THANH_TIEN) - TO_NUMBER(item.SO_LUONG) * TO_NUMBER(item.DON_GIA)) > 1) > 0`, BIEU_THUC_CHUAN_HOA: `Biểu thức chuẩn nên đọc cùng họ cột SO_LUONG, DON_GIA_BH/DON_GIA_BV/DON_GIA và THANH_TIEN_BH/THANH_TIEN_BV/THANH_TIEN; runtime giữ nguyên cú pháp cũ để tránh đổi hành vi.`, CANH_BAO: `🔴 Sai tiền (đã loại sai số làm tròn): THANH_TIEN khác SO_LUONG × DON_GIA vượt quá 1 đồng.`, TRANG_THAI: 'ON' },
  { id: 'HD-020', MA_LUAT: 'HD_20', TEN_QUY_TAC: `Trùng CLS trong cùng ngày (chỉ áp dụng CLS)`, DIEU_KIEN: `COUNT_IF(XML3, item => (item.MA_NHOM == '3' OR item.MA_NHOM == '4') AND !IS_EMPTY(item.MA_DICH_VU) AND COUNT_IF(XML3, other => other.MA_DICH_VU == item.MA_DICH_VU AND SUBSTR(other.NGAY_YL, 1, 8) == SUBSTR(item.NGAY_YL, 1, 8)) > 1) > 0`, CANH_BAO: `🟠 Trùng CLS bất thường: Cùng mã dịch vụ CLS, cùng ngày y lệnh, xuất hiện nhiều hơn 1 lần.`, TRANG_THAI: 'ON' },
  { id: 'HD-021', MA_LUAT: 'HD_21', TEN_QUY_TAC: `Ngày giường vượt số ngày điều trị (nội trú/nội trú ban ngày)`, DIEU_KIEN: `COUNT_IF(XML3, item => item.MA_NHOM == '2' AND XML1.MA_LOAI_KCB IN ('03','04','09') AND !IS_EMPTY(item.SO_LUONG) AND !IS_EMPTY(XML1.NGAY_VAO) AND !IS_EMPTY(XML1.NGAY_RA) AND TO_NUMBER(item.SO_LUONG) > (DATEDIFF_DAY(XML1.NGAY_VAO, XML1.NGAY_RA) + 1)) > 0`, CANH_BAO: `🔴 Vượt ngày giường điều trị nội trú/nội trú ban ngày: Số ngày giường bệnh vượt quá số ngày điều trị (NGAY_RA - NGAY_VAO + 1).`, TRANG_THAI: 'ON' },
  { id: 'HD-022', MA_LUAT: 'HD_22', TEN_QUY_TAC: `DV ngoài danh mục được phép`, DIEU_KIEN: `!IS_EMPTY(MA_DICH_VU) AND IS_EMPTY(DM_DICH_VU[MA_DICH_VU])`, BIEU_THUC_CHUAN_HOA: `Biểu thức chuẩn cần tường minh scope dòng hiện tại, ví dụ CURRENT.MA_DICH_VU; runtime giữ nguyên để không đổi cú pháp engine đang lưu hành.`, CANH_BAO: `🔴 Không thuộc phạm vi thanh toán`, TRANG_THAI: 'ON' },
  { id: 'HD-023', MA_LUAT: 'HD_23', TEN_QUY_TAC: `DV vượt phạm vi chuyên môn BV`, DIEU_KIEN: `!IS_EMPTY(MA_DICH_VU) AND MA_DICH_VU NOT IN DM_KY_THUAT_BV`, BIEU_THUC_CHUAN_HOA: `Biểu thức chuẩn cần tường minh scope dòng hiện tại, ví dụ CURRENT.MA_DICH_VU; runtime giữ nguyên để không đổi cú pháp engine đang lưu hành.`, CANH_BAO: `🔴 Vượt phạm vi chuyên môn (không thanh toán)`, TRANG_THAI: 'ON' },
]);

export const layDanhSachLuatHopDongHardcoded = () => CACHE_RULES_HARDCODED.map((row) => ({ ...row }));
