/**
 * Cột mẫu Excel (file mẫu) theo từng tab Quản lý danh mục — dùng chung UI + QA XML.
 * Đối soát XML: mỗi `<Truong cot="…">` phải khớp đúng một tên cột trong danh sách này (theo từng maBang).
 */

export const MAU_EXCEL_CHUAN = {
  DANH_MUC_ICD10: ['MÃ BỆNH', 'MÃ BỆNH KHÔNG DẤU', 'DISEASE NAME', 'TÊN BỆNH'],
  DANH_MUC_ICD10_CAP_CUU: ['ID', 'Nhom_Benh', 'Tinh_Trang_Benh', 'ICD_Chinh', 'Ly_Do_Nhap_Vien', 'ICD_Kem_Theo', 'Ngoai_Le', 'Tu_Khoa'],
  DANH_MUC_ICD10_KE_DON_TREN_30_NGAY: ['TT', 'Mã TT', 'Danh mục bệnh theo các chuyên khoa', 'Mã bệnh theo ICD 10'],
  THONG_TIN_CO_SO: ['MA_CSKCB', 'TEN_CSKCB', 'DIA_CHI', 'TUYEN', 'HANG'],
  DANH_MUC_KHOA_LS_M01: ['STT', 'MA_KHOA', 'TEN_KHOA', 'BAN_KHAM', 'GIUONG_PD', 'GIUONG_TK', 'GIUONG_HSTC', 'GIUONG_HSCC', 'TU_NGAY', 'DEN_NGAY', 'MA_CSKCB', 'ID', 'MA_LOAI_KCB', 'LDLK', 'LIEN_KHOA', 'GIUONG_2015'],
  DANH_MUC_NHAN_SU: ['DEN_NGAY', 'STT', 'MA_LOAI_KCB', 'MA_KHOA', 'TEN_KHOA', 'MA_BHXH', 'HO_TEN', 'GIOI_TINH', 'NGAY_SINH', 'SO_CCCD', 'CHUCDANH_NN', 'VI_TRI', 'MACCHN', 'NGAYCAP_CCHN', 'NOICAP_CCHN', 'PHAMVI_CM', 'PHAMVI_CMBS', 'DVKT_KHAC', 'VB_PHANCONG', 'THOIGIAN_DK', 'THOIGIAN_NGAY', 'THOIGIAN_TUAN', 'CSKCB_KHAC', 'CSKCB_CGKT', 'QD_CGKT', 'TU_NGAY', 'MA_DANTOC', 'ID'],
  DANH_MUC_MAPPING_NGUOI_HANH_NGHE: ['STT', 'MA_TUONG_DUONG', 'TEN_DVKT', 'MA_CHUYEN_KHOA', 'PHAMVI_CM_CAN', 'SO_NV_DU_DIEU_KIEN', 'DANH_SACH_NGUOI_THUC_HIEN', 'DANH_SACH_MACCHN', 'DANH_SACH_MA_BHXH', 'TRANG_THAI'],
  DVKT_PHAMVI_MAPPING: ['PREFIX_DVKT', 'PHAMVI_CM_OK', 'CHUCDANH_NN_OK', 'NHOM_DVKT'],
  DVKT_EQUIP_DVKT_MAP: ['PREFIX_DVKT', 'MA_MAY_PREFIX', 'GHI_CHU'],
  DANH_MUC_THUOC_MAU_M03: ['STT', 'MA_THUOC', 'TEN_HOAT_CHAT', 'TEN_THUOC', 'DON_VI_TINH', 'HAM_LUONG', 'DUONG_DUNG', 'MA_DUONG_DUNG', 'DANG_BAO_CHE', 'SO_DANG_KY', 'QUY_CACH', 'DON_GIA', 'DON_GIA_TT', 'GIA_BH_TT', 'TT_THAU', 'TYLE_TT_BH', 'LOAI_THUOC', 'LOAI_THAU', 'NHA_SX', 'NUOC_SX', 'NHA_THAU', 'KIEU_THAU', 'GIA_KHOA_KHO', 'GIA_BB_CD', 'PP_CHEBIEN', 'VITRI_YHCT', 'MA_CSKCB_THUOC', 'TU_NGAY', 'DEN_NGAY', 'MA_CSKCB', 'SO_LUONG', 'ID'],
  DANH_MUC_TUONG_TAC_THUOC: ['id', 'TRANG_THAI', 'MA_TUONG_TAC', 'MA_THUOC_A', 'MA_THUOC_B', 'NOI_DUNG_TUONG_TAC', 'CANH_BAO_HE_THONG', 'MUC_DO_CANH_BAO', 'DU_LIEU_CAP_DOI_DAY_DU'],
  DANH_MUC_VAT_TU_M04: ['STT', 'MA_VAT_TU', 'NHOM_VAT_TU', 'TEN_VAT_TU', 'MA_HIEU', 'SO_LUU_HANH', 'TINHNANG_KT', 'QUY_CACH', 'DON_VI_TINH', 'DON_GIA', 'GIA_BH_TT', 'TT_THAU', 'TYLE_TT_BH', 'LOAI_THAU', 'NHA_SX', 'NUOC_SX', 'NHA_THAU', 'NHA_PP', 'TU_NGAY', 'DEN_NGAY', 'MA_CSKCB'],
  DANH_MUC_DVKT_M05: ['STT', 'MA_DICH_VU', 'TEN_DICH_VU', 'TEN_DVKT_GIA', 'DON_GIA', 'QUY_TRINH', 'CS_THUCHIEN', 'TINHTRANG_DV', 'MA_GIA', 'TEN_GIA', 'GIA_TT_BHYT', 'MA_PTTT', 'TU_NGAY', 'DEN_NGAY', 'MA_CSKCB', 'PHAN_LOAI_PTTT', 'GHICHU', 'QUYET_DINH'],
  DANH_MUC_GIUONG_BAN_KHAM_BV: [
    'STT', 'MA_TUONG_DUONG', 'TEN_DVKT_PHEDUYET', 'TEN_DVKT_GIA', 'PHAN_LOAI_PTTT', 'DON_GIA',
    'GHICHU', 'QUYET_DINH', 'TUNGAY', 'DENNGAY', 'CSKCB_CGKT', 'CSKCB_CLS', 'ID',
  ],
  DANH_MUC_TRANG_THIET_BI_M06: ['STT', 'TEN_TB', 'KY_HIEU', 'CONGTY_SX', 'NUOC_SX', 'NAM_SX', 'NAM_SD', 'MA_MAY', 'SO_LUU_HANH', 'HD_TU', 'HD_DEN', 'TU_NGAY', 'DEN_NGAY', 'MA_CSKCB', 'ID'],
  DANH_MUC_HA_TANG: ['MA_TIEU_CHI', 'TEN_TIEU_CHI', 'TRANG_THAI', 'GHI_CHU'],
};

export const MA_BANG_CO_MAU_EXCEL = Object.keys(MAU_EXCEL_CHUAN);
